import { querySnowflake } from "@/lib/snowflake";
import { NextResponse } from "next/server";

export const dynamic = "force-dynamic";

export async function GET() {
  const [kpis, porCanal, porCiudad, tendenciaDiaria, tasaRechazo, topComerciosMonto, alertasSeveridad, modelosFraude] = await Promise.all([
    querySnowflake(`SELECT 
      (SELECT COUNT(*) FROM CREDIBANCO_HOL.PAGOS.AUTORIZACIONES) AS TOTAL_AUT,
      (SELECT COUNT(*) FROM CREDIBANCO_HOL.PAGOS.AUTORIZACIONES WHERE CODIGO_RESPUESTA='00') AS APROBADAS,
      (SELECT COUNT(*) FROM CREDIBANCO_HOL.COMERCIOS.COMERCIOS) AS COMERCIOS,
      (SELECT COUNT(DISTINCT CIUDAD) FROM CREDIBANCO_HOL.PAGOS.AUTORIZACIONES) AS CIUDADES,
      (SELECT SUM(MONTO) FROM CREDIBANCO_HOL.PAGOS.AUTORIZACIONES WHERE CODIGO_RESPUESTA='00') AS MONTO_TOTAL,
      (SELECT AVG(MONTO) FROM CREDIBANCO_HOL.PAGOS.AUTORIZACIONES WHERE CODIGO_RESPUESTA='00') AS TICKET_PROM,
      (SELECT COUNT(*) FROM CREDIBANCO_HOL.RIESGO.ALERTAS) AS ALERTAS,
      (SELECT COUNT(*) FROM CREDIBANCO_HOL.RIESGO.ALERTAS WHERE SEVERIDAD='CRITICA') AS ALERTAS_CRITICAS,
      (SELECT COUNT(*) FROM CREDIBANCO_HOL.PAGOS.LIQUIDACIONES) AS LIQUIDACIONES,
      (SELECT SUM(MONTO_LIQUIDADO) FROM CREDIBANCO_HOL.PAGOS.LIQUIDACIONES) AS MONTO_LIQUIDADO`),
    querySnowflake(`SELECT CANAL, COUNT(*) AS TX, SUM(MONTO) AS MONTO, ROUND(AVG(MONTO)) AS TICKET
      FROM CREDIBANCO_HOL.PAGOS.AUTORIZACIONES WHERE CODIGO_RESPUESTA='00' GROUP BY CANAL ORDER BY TX DESC`),
    querySnowflake(`SELECT CIUDAD, COUNT(*) AS TX, SUM(MONTO) AS MONTO, 
      ROUND(SUM(CASE WHEN CODIGO_RESPUESTA='00' THEN 1 ELSE 0 END)::FLOAT/COUNT(*)*100,1) AS TASA_APROB
      FROM CREDIBANCO_HOL.PAGOS.AUTORIZACIONES GROUP BY CIUDAD ORDER BY TX DESC LIMIT 8`),
    querySnowflake(`SELECT DATE(FECHA_HORA) AS FECHA, COUNT(*) AS TX, SUM(MONTO) AS MONTO,
      SUM(CASE WHEN CODIGO_RESPUESTA!='00' THEN 1 ELSE 0 END) AS RECHAZADAS
      FROM CREDIBANCO_HOL.PAGOS.AUTORIZACIONES GROUP BY FECHA ORDER BY FECHA DESC LIMIT 30`),
    querySnowflake(`SELECT CIUDAD, 
      ROUND(SUM(CASE WHEN CODIGO_RESPUESTA!='00' THEN 1 ELSE 0 END)::FLOAT/NULLIF(COUNT(*),0)*100,2) AS TASA_RECHAZO,
      COUNT(*) AS TOTAL
      FROM CREDIBANCO_HOL.PAGOS.AUTORIZACIONES GROUP BY CIUDAD ORDER BY TASA_RECHAZO DESC LIMIT 8`),
    querySnowflake(`SELECT c.RAZON_SOCIAL, SUM(a.MONTO) AS MONTO_TOTAL, COUNT(*) AS TX
      FROM CREDIBANCO_HOL.PAGOS.AUTORIZACIONES a JOIN CREDIBANCO_HOL.COMERCIOS.COMERCIOS c ON a.COMERCIO_ID=c.COMERCIO_ID
      WHERE a.CODIGO_RESPUESTA='00' GROUP BY c.RAZON_SOCIAL ORDER BY MONTO_TOTAL DESC LIMIT 10`),
    querySnowflake(`SELECT SEVERIDAD, COUNT(*) AS TOTAL FROM CREDIBANCO_HOL.RIESGO.ALERTAS GROUP BY SEVERIDAD ORDER BY 
      CASE SEVERIDAD WHEN 'CRITICA' THEN 1 WHEN 'ALTA' THEN 2 WHEN 'MEDIA' THEN 3 ELSE 4 END`),
    querySnowflake(`SELECT TIPO AS TIPO_ALERTA, COUNT(*) AS TOTAL FROM CREDIBANCO_HOL.RIESGO.ALERTAS GROUP BY TIPO ORDER BY TOTAL DESC LIMIT 6`),
  ]);

  return NextResponse.json({
    kpis: kpis[0],
    porCanal, porCiudad, tendenciaDiaria: tendenciaDiaria.reverse(),
    tasaRechazo, topComerciosMonto, alertasSeveridad, modelosFraude
  });
}
