import { querySnowflake } from "@/lib/snowflake";
import { NextResponse } from "next/server";

export const dynamic = "force-dynamic";

export async function GET() {
  const [byTipo, bySeveridad, byCiudad, highRisk, governance] = await Promise.all([
    querySnowflake(`SELECT TIPO, COUNT(*) AS TOTAL FROM CREDIBANCO_HOL.RIESGO.ALERTAS GROUP BY TIPO ORDER BY TOTAL DESC`),
    querySnowflake(`SELECT SEVERIDAD, COUNT(*) AS TOTAL FROM CREDIBANCO_HOL.RIESGO.ALERTAS GROUP BY SEVERIDAD
      ORDER BY CASE SEVERIDAD WHEN 'CRITICA' THEN 1 WHEN 'ALTA' THEN 2 WHEN 'MEDIA' THEN 3 ELSE 4 END`),
    querySnowflake(`SELECT c.CIUDAD, COUNT(*) AS ALERTAS
      FROM CREDIBANCO_HOL.RIESGO.ALERTAS al JOIN CREDIBANCO_HOL.COMERCIOS.COMERCIOS c ON al.COMERCIO_ID=c.COMERCIO_ID
      GROUP BY c.CIUDAD ORDER BY ALERTAS DESC`),
    querySnowflake(`SELECT c.RAZON_SOCIAL, c.CIUDAD, COUNT(a2.*) AS TX,
      ROUND(SUM(CASE WHEN a2.CODIGO_RESPUESTA!='00' THEN 1 ELSE 0 END)::FLOAT/NULLIF(COUNT(*),0)*100,1) AS TASA_RECHAZO,
      COUNT(al.*) AS ALERTAS
      FROM CREDIBANCO_HOL.COMERCIOS.COMERCIOS c
      JOIN CREDIBANCO_HOL.PAGOS.AUTORIZACIONES a2 ON c.COMERCIO_ID=a2.COMERCIO_ID
      LEFT JOIN CREDIBANCO_HOL.RIESGO.ALERTAS al ON c.COMERCIO_ID=al.COMERCIO_ID
      GROUP BY c.RAZON_SOCIAL, c.CIUDAD HAVING TASA_RECHAZO > 10 ORDER BY TASA_RECHAZO DESC LIMIT 15`),
    querySnowflake(`SELECT AGENTE, MODELO_LLM, COUNT(*) AS USOS, SUM(TOKENS_ENTRADA+TOKENS_SALIDA) AS TOKENS_TOTAL,
      MIN(FECHA) AS PRIMERA_USO, MAX(FECHA) AS ULTIMO_USO
      FROM CREDIBANCO_HOL.GOBIERNO.REGISTRO_USO_IA GROUP BY AGENTE, MODELO_LLM ORDER BY USOS DESC`),
  ]);

  return NextResponse.json({ byTipo, bySeveridad, byCiudad, highRisk, governance });
}
