import { querySnowflake } from "@/lib/snowflake";
import { NextResponse } from "next/server";

export const dynamic = "force-dynamic";

export async function GET() {
  const [byEstado, byMerchant, authVsSettle, avgTime] = await Promise.all([
    querySnowflake(`SELECT ESTADO, COUNT(*) AS TOTAL, SUM(MONTO_LIQUIDADO) AS MONTO
      FROM CREDIBANCO_HOL.PAGOS.LIQUIDACIONES GROUP BY ESTADO ORDER BY TOTAL DESC`),
    querySnowflake(`SELECT c.RAZON_SOCIAL, SUM(l.MONTO_LIQUIDADO) AS MONTO_LIQ, COUNT(*) AS LIQUIDACIONES
      FROM CREDIBANCO_HOL.PAGOS.LIQUIDACIONES l JOIN CREDIBANCO_HOL.COMERCIOS.COMERCIOS c ON l.COMERCIO_ID=c.COMERCIO_ID
      GROUP BY c.RAZON_SOCIAL ORDER BY MONTO_LIQ DESC LIMIT 15`),
    querySnowflake(`SELECT c.RAZON_SOCIAL,
      SUM(a.MONTO) AS MONTO_AUTH, SUM(l.MONTO_LIQUIDADO) AS MONTO_LIQ
      FROM CREDIBANCO_HOL.COMERCIOS.COMERCIOS c
      JOIN CREDIBANCO_HOL.PAGOS.AUTORIZACIONES a ON c.COMERCIO_ID=a.COMERCIO_ID AND a.CODIGO_RESPUESTA='00'
      JOIN CREDIBANCO_HOL.PAGOS.LIQUIDACIONES l ON c.COMERCIO_ID=l.COMERCIO_ID
      GROUP BY c.RAZON_SOCIAL ORDER BY MONTO_AUTH DESC LIMIT 10`),
    querySnowflake(`SELECT ESTADO, ROUND(AVG(DATEDIFF('day', FECHA_LIQUIDACION, CURRENT_DATE())),1) AS DIAS_PROM, COUNT(*) AS TOTAL
      FROM CREDIBANCO_HOL.PAGOS.LIQUIDACIONES GROUP BY ESTADO ORDER BY DIAS_PROM DESC`),
  ]);

  return NextResponse.json({ byEstado, byMerchant, authVsSettle, avgTime });
}
