/* master_load_git.sql — Load data from Git repository (no local files needed)
   Prerequisite: HOL_REPO must be created and fetched first:
     CREATE GIT REPOSITORY CREDIBANCO_HOL.PLATAFORMA.HOL_REPO
       API_INTEGRATION = GITHUB_GIT_INTEGRATION
       ORIGIN = 'https://github.com/sfc-gh-jcastaneda/credibanco-hol.git';
     ALTER GIT REPOSITORY CREDIBANCO_HOL.PLATAFORMA.HOL_REPO FETCH;
*/
USE ROLE ACCOUNTADMIN;
USE DATABASE CREDIBANCO_HOL;
USE WAREHOUSE CREDIBANCO_HOL_WH;
CREATE OR REPLACE FILE FORMAT CREDIBANCO_HOL.PLATAFORMA.FF_PARQUET TYPE = PARQUET;

-- Truncate all tables first (idempotency)
TRUNCATE TABLE IF EXISTS CREDIBANCO_HOL.COMERCIOS.COMERCIOS;
TRUNCATE TABLE IF EXISTS CREDIBANCO_HOL.CLIENTES.TARJETAHABIENTES;
TRUNCATE TABLE IF EXISTS CREDIBANCO_HOL.CLIENTES.PRODUCTOS;
TRUNCATE TABLE IF EXISTS CREDIBANCO_HOL.PAGOS.AUTORIZACIONES;
TRUNCATE TABLE IF EXISTS CREDIBANCO_HOL.PAGOS.LIQUIDACIONES;
TRUNCATE TABLE IF EXISTS CREDIBANCO_HOL.PAGOS.AUTORIZACIONES_JSON;
TRUNCATE TABLE IF EXISTS CREDIBANCO_HOL.PAGOS.AUTORIZACIONES_STREAMING;
TRUNCATE TABLE IF EXISTS CREDIBANCO_HOL.PAGOS.AUTORIZACIONES_METADATA_RAW;
TRUNCATE TABLE IF EXISTS CREDIBANCO_HOL.RIESGO.RED_TRANSACCIONAL;
TRUNCATE TABLE IF EXISTS CREDIBANCO_HOL.RIESGO.CONTRACARGOS;
TRUNCATE TABLE IF EXISTS CREDIBANCO_HOL.RIESGO.ALERTAS;
TRUNCATE TABLE IF EXISTS CREDIBANCO_HOL.TURISMO.AGREGADOS_TURISMO;
TRUNCATE TABLE IF EXISTS CREDIBANCO_HOL.GOBIERNO.CATALOGO_CONTROLES;
TRUNCATE TABLE IF EXISTS CREDIBANCO_HOL.GOBIERNO.CONTRATOS_DATOS;
TRUNCATE TABLE IF EXISTS CREDIBANCO_HOL.GOBIERNO.CATALOGO_CASOS_USO;
TRUNCATE TABLE IF EXISTS CREDIBANCO_HOL.ANALITICA.TRAIN_ANOMALIAS;
TRUNCATE TABLE IF EXISTS CREDIBANCO_HOL.ANALITICA.TRAIN_RIESGO_COMERCIO;
TRUNCATE TABLE IF EXISTS CREDIBANCO_HOL.ANALITICA.RESULTADO_ANOMALIAS;
TRUNCATE TABLE IF EXISTS CREDIBANCO_HOL.ANALITICA.FEATURES_RIESGO_COMERCIO;
TRUNCATE TABLE IF EXISTS CREDIBANCO_HOL.CUMPLIMIENTO.DOCUMENTOS_SARLAFT;
TRUNCATE TABLE IF EXISTS CREDIBANCO_HOL.ANALITICA.ALERTAS_RIESGO;
TRUNCATE TABLE IF EXISTS CREDIBANCO_HOL.MIGRACION.EQUIVALENCIAS_SQL;
TRUNCATE TABLE IF EXISTS CREDIBANCO_HOL.MIGRACION.RECONCILIACION_DIARIA;
TRUNCATE TABLE IF EXISTS CREDIBANCO_HOL.PLATAFORMA.CONFIG_DATAOPS;
TRUNCATE TABLE IF EXISTS CREDIBANCO_HOL.COMERCIOS.RED_COMERCIOS;

COPY INTO CREDIBANCO_HOL.COMERCIOS.COMERCIOS FROM (SELECT $1:COMERCIO_ID AS COMERCIO_ID, $1:NIT AS NIT, $1:RAZON_SOCIAL AS RAZON_SOCIAL, $1:CIUDAD AS CIUDAD, $1:MCC AS MCC, $1:ORIGEN_REGISTRO AS ORIGEN_REGISTRO, TO_DATE(TO_TIMESTAMP($1:FECHA_AFILIACION::NUMBER / 1000)) AS FECHA_AFILIACION FROM @CREDIBANCO_HOL.PLATAFORMA.HOL_REPO/branches/main/data/comercios.parquet (FILE_FORMAT => 'CREDIBANCO_HOL.PLATAFORMA.FF_PARQUET')) FORCE = TRUE;
COPY INTO CREDIBANCO_HOL.CLIENTES.TARJETAHABIENTES FROM (SELECT $1:TARJETAHABIENTE_ID AS TARJETAHABIENTE_ID, $1:NOMBRE AS NOMBRE, $1:DOCUMENTO AS DOCUMENTO, $1:CELULAR AS CELULAR, $1:PAN_SINTETICO AS PAN_SINTETICO, TO_DATE(TO_TIMESTAMP($1:FECHA_NACIMIENTO::NUMBER / 1000)) AS FECHA_NACIMIENTO, $1:NOMBRE_COMPLETO AS NOMBRE_COMPLETO, $1:CORREO AS CORREO, $1:NUMERO_DOCUMENTO AS NUMERO_DOCUMENTO FROM @CREDIBANCO_HOL.PLATAFORMA.HOL_REPO/branches/main/data/tarjetahabientes.parquet (FILE_FORMAT => 'CREDIBANCO_HOL.PLATAFORMA.FF_PARQUET')) FORCE = TRUE;
COPY INTO CREDIBANCO_HOL.CLIENTES.PRODUCTOS FROM @CREDIBANCO_HOL.PLATAFORMA.HOL_REPO/branches/main/data/productos.parquet FILE_FORMAT = (TYPE = PARQUET) MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE FORCE = TRUE;
COPY INTO CREDIBANCO_HOL.PAGOS.AUTORIZACIONES FROM (SELECT $1:AUTORIZACION_ID AS AUTORIZACION_ID, $1:COMERCIO_ID AS COMERCIO_ID, $1:TARJETAHABIENTE_ID AS TARJETAHABIENTE_ID, $1:PAN AS PAN, $1:MCC AS MCC, $1:CIUDAD AS CIUDAD, TO_TIMESTAMP_NTZ($1:FECHA_HORA::NUMBER / 1000000) AS FECHA_HORA, $1:MONTO AS MONTO, $1:CODIGO_RESPUESTA AS CODIGO_RESPUESTA, $1:CANAL AS CANAL FROM @CREDIBANCO_HOL.PLATAFORMA.HOL_REPO/branches/main/data/autorizaciones.parquet (FILE_FORMAT => 'CREDIBANCO_HOL.PLATAFORMA.FF_PARQUET')) FORCE = TRUE;
COPY INTO CREDIBANCO_HOL.PAGOS.LIQUIDACIONES FROM (SELECT $1:LIQUIDACION_ID AS LIQUIDACION_ID, $1:AUTORIZACION_ID AS AUTORIZACION_ID, $1:COMERCIO_ID AS COMERCIO_ID, $1:MONTO_LIQUIDADO AS MONTO_LIQUIDADO, TO_DATE(TO_TIMESTAMP($1:FECHA_LIQUIDACION::NUMBER / 1000)) AS FECHA_LIQUIDACION, $1:ESTADO AS ESTADO FROM @CREDIBANCO_HOL.PLATAFORMA.HOL_REPO/branches/main/data/liquidaciones.parquet (FILE_FORMAT => 'CREDIBANCO_HOL.PLATAFORMA.FF_PARQUET')) FORCE = TRUE;
COPY INTO CREDIBANCO_HOL.PAGOS.AUTORIZACIONES_JSON FROM (SELECT $1:AUTORIZACION_ID AS AUTORIZACION_ID, PARSE_JSON($1:METADATA_DISPOSITIVO::VARCHAR) AS METADATA_DISPOSITIVO FROM @CREDIBANCO_HOL.PLATAFORMA.HOL_REPO/branches/main/data/autorizaciones_json.parquet (FILE_FORMAT => 'CREDIBANCO_HOL.PLATAFORMA.FF_PARQUET')) FORCE = TRUE;
COPY INTO CREDIBANCO_HOL.PAGOS.AUTORIZACIONES_STREAMING FROM (SELECT $1:AUTORIZACION_ID AS AUTORIZACION_ID, $1:COMERCIO_ID AS COMERCIO_ID, $1:PAN AS PAN, $1:CIUDAD AS CIUDAD, $1:MONTO AS MONTO, $1:CREATETIME AS CREATETIME, $1:OFFSET_PARTITION AS OFFSET_PARTITION, PARSE_JSON($1:RECORD_CONTENT::VARCHAR) AS RECORD_CONTENT FROM @CREDIBANCO_HOL.PLATAFORMA.HOL_REPO/branches/main/data/autorizaciones_streaming.parquet (FILE_FORMAT => 'CREDIBANCO_HOL.PLATAFORMA.FF_PARQUET')) FORCE = TRUE;
COPY INTO CREDIBANCO_HOL.PAGOS.AUTORIZACIONES_METADATA_RAW FROM (SELECT $1:AUTORIZACION_ID AS AUTORIZACION_ID, PARSE_JSON($1:METADATA::VARCHAR) AS METADATA FROM @CREDIBANCO_HOL.PLATAFORMA.HOL_REPO/branches/main/data/autorizaciones_metadata_raw.parquet (FILE_FORMAT => 'CREDIBANCO_HOL.PLATAFORMA.FF_PARQUET')) FORCE = TRUE;
COPY INTO CREDIBANCO_HOL.RIESGO.RED_TRANSACCIONAL FROM @CREDIBANCO_HOL.PLATAFORMA.HOL_REPO/branches/main/data/red_transaccional.parquet FILE_FORMAT = (TYPE = PARQUET) MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE FORCE = TRUE;
COPY INTO CREDIBANCO_HOL.RIESGO.CONTRACARGOS FROM (SELECT $1:CONTRACARGO_ID AS CONTRACARGO_ID, $1:AUTORIZACION_ID AS AUTORIZACION_ID, $1:MOTIVO AS MOTIVO, $1:MONTO AS MONTO, TO_DATE(TO_TIMESTAMP($1:FECHA::NUMBER / 1000)) AS FECHA, $1:ESTADO AS ESTADO FROM @CREDIBANCO_HOL.PLATAFORMA.HOL_REPO/branches/main/data/contracargos.parquet (FILE_FORMAT => 'CREDIBANCO_HOL.PLATAFORMA.FF_PARQUET')) FORCE = TRUE;
COPY INTO CREDIBANCO_HOL.RIESGO.ALERTAS FROM (SELECT $1:ALERTA_ID AS ALERTA_ID, $1:TIPO AS TIPO, $1:COMERCIO_ID AS COMERCIO_ID, $1:SEVERIDAD AS SEVERIDAD, TO_TIMESTAMP_NTZ($1:FECHA_HORA::NUMBER / 1000000) AS FECHA_HORA, $1:DESCRIPCION AS DESCRIPCION FROM @CREDIBANCO_HOL.PLATAFORMA.HOL_REPO/branches/main/data/alertas.parquet (FILE_FORMAT => 'CREDIBANCO_HOL.PLATAFORMA.FF_PARQUET')) FORCE = TRUE;
COPY INTO CREDIBANCO_HOL.TURISMO.AGREGADOS_TURISMO FROM (SELECT $1:REGION AS REGION, $1:MCC AS MCC, TO_DATE(TO_TIMESTAMP($1:MES::NUMBER / 1000)) AS MES, $1:NUM_TRANSACCIONES AS NUM_TRANSACCIONES, $1:MONTO_TOTAL AS MONTO_TOTAL FROM @CREDIBANCO_HOL.PLATAFORMA.HOL_REPO/branches/main/data/agregados_turismo.parquet (FILE_FORMAT => 'CREDIBANCO_HOL.PLATAFORMA.FF_PARQUET')) FORCE = TRUE;
COPY INTO CREDIBANCO_HOL.GOBIERNO.CATALOGO_CONTROLES FROM @CREDIBANCO_HOL.PLATAFORMA.HOL_REPO/branches/main/data/catalogo_controles.parquet FILE_FORMAT = (TYPE = PARQUET) MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE FORCE = TRUE;
COPY INTO CREDIBANCO_HOL.GOBIERNO.CONTRATOS_DATOS FROM @CREDIBANCO_HOL.PLATAFORMA.HOL_REPO/branches/main/data/contratos_datos.parquet FILE_FORMAT = (TYPE = PARQUET) MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE FORCE = TRUE;
COPY INTO CREDIBANCO_HOL.GOBIERNO.CATALOGO_CASOS_USO FROM (SELECT $1:CASO_USO_ID AS CASO_USO_ID, $1:NOMBRE AS NOMBRE, $1:DESCRIPCION AS DESCRIPCION, $1:DOMINIO AS DOMINIO, PARSE_JSON($1:OBJETOS_FUENTE::VARCHAR) AS OBJETOS_FUENTE, $1:AREA_NEGOCIO AS AREA_NEGOCIO, $1:ESTADO AS ESTADO FROM @CREDIBANCO_HOL.PLATAFORMA.HOL_REPO/branches/main/data/catalogo_casos_uso.parquet (FILE_FORMAT => 'CREDIBANCO_HOL.PLATAFORMA.FF_PARQUET')) FORCE = TRUE;
COPY INTO CREDIBANCO_HOL.ANALITICA.TRAIN_ANOMALIAS FROM (SELECT $1:COMERCIO_ID AS COMERCIO_ID, TO_DATE(TO_TIMESTAMP($1:FECHA::NUMBER / 1000)) AS FECHA, $1:MONTO_TOTAL AS MONTO_TOTAL FROM @CREDIBANCO_HOL.PLATAFORMA.HOL_REPO/branches/main/data/train_anomalias.parquet (FILE_FORMAT => 'CREDIBANCO_HOL.PLATAFORMA.FF_PARQUET')) FORCE = TRUE;
COPY INTO CREDIBANCO_HOL.ANALITICA.TRAIN_RIESGO_COMERCIO FROM @CREDIBANCO_HOL.PLATAFORMA.HOL_REPO/branches/main/data/train_riesgo_comercio.parquet FILE_FORMAT = (TYPE = PARQUET) MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE FORCE = TRUE;
COPY INTO CREDIBANCO_HOL.ANALITICA.RESULTADO_ANOMALIAS FROM (SELECT $1:COMERCIO_ID AS COMERCIO_ID, TO_DATE(TO_TIMESTAMP($1:FECHA::NUMBER / 1000)) AS FECHA, $1:MONTO_TOTAL AS MONTO_TOTAL, $1:IS_ANOMALY AS IS_ANOMALY, $1:PERCENTILE AS PERCENTILE, $1:DISTANCE AS DISTANCE, $1:FORECAST AS FORECAST FROM @CREDIBANCO_HOL.PLATAFORMA.HOL_REPO/branches/main/data/resultado_anomalias.parquet (FILE_FORMAT => 'CREDIBANCO_HOL.PLATAFORMA.FF_PARQUET')) FORCE = TRUE;
COPY INTO CREDIBANCO_HOL.ANALITICA.FEATURES_RIESGO_COMERCIO FROM @CREDIBANCO_HOL.PLATAFORMA.HOL_REPO/branches/main/data/features_riesgo_comercio.parquet FILE_FORMAT = (TYPE = PARQUET) MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE FORCE = TRUE;
COPY INTO CREDIBANCO_HOL.CUMPLIMIENTO.DOCUMENTOS_SARLAFT FROM @CREDIBANCO_HOL.PLATAFORMA.HOL_REPO/branches/main/data/documentos_sarlaft.parquet FILE_FORMAT = (TYPE = PARQUET) MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE FORCE = TRUE;
COPY INTO CREDIBANCO_HOL.ANALITICA.ALERTAS_RIESGO FROM @CREDIBANCO_HOL.PLATAFORMA.HOL_REPO/branches/main/data/alertas_riesgo.parquet FILE_FORMAT = (TYPE = PARQUET) MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE FORCE = TRUE;
COPY INTO CREDIBANCO_HOL.MIGRACION.EQUIVALENCIAS_SQL FROM @CREDIBANCO_HOL.PLATAFORMA.HOL_REPO/branches/main/data/equivalencias_sql.parquet FILE_FORMAT = (TYPE = PARQUET) MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE FORCE = TRUE;
COPY INTO CREDIBANCO_HOL.PLATAFORMA.CONFIG_DATAOPS FROM @CREDIBANCO_HOL.PLATAFORMA.HOL_REPO/branches/main/data/config_dataops.parquet FILE_FORMAT = (TYPE = PARQUET) MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE FORCE = TRUE;
COPY INTO CREDIBANCO_HOL.COMERCIOS.RED_COMERCIOS FROM @CREDIBANCO_HOL.PLATAFORMA.HOL_REPO/branches/main/data/red_comercios.parquet FILE_FORMAT = (TYPE = PARQUET) MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE FORCE = TRUE;

-- Enable change tracking for Dynamic Tables
ALTER TABLE CREDIBANCO_HOL.PAGOS.AUTORIZACIONES SET CHANGE_TRACKING = TRUE;

-- Enable time travel for clone demos
ALTER TABLE CREDIBANCO_HOL.PAGOS.AUTORIZACIONES SET DATA_RETENTION_TIME_IN_DAYS = 1;

-- Attach RAP (drop first for idempotency)
ALTER TABLE CREDIBANCO_HOL.PAGOS.AUTORIZACIONES DROP ALL ROW ACCESS POLICIES;
ALTER TABLE CREDIBANCO_HOL.PAGOS.AUTORIZACIONES ADD ROW ACCESS POLICY CREDIBANCO_HOL.GOBIERNO.RAP_AUTORIZACIONES ON (CODIGO_RESPUESTA);

SELECT 'MASTER_LOAD_OK' AS status, (SELECT COUNT(*) FROM PAGOS.AUTORIZACIONES) AS autorizaciones, (SELECT COUNT(*) FROM ANALITICA.TRAIN_ANOMALIAS) AS train_anomalias;