/* ============================================================================
   MASTER SETUP — CredibanCo HOL V3
   Script 100% autocontenido. Funciona en CUALQUIER cuenta limpia.
   Ejecutar como ACCOUNTADMIN. No asume que existe ningun usuario ni objeto.
   ========================================================================= */

USE ROLE ACCOUNTADMIN;

-- ============================================================================
-- 0. CONFIGURACION DE CUENTA + LIMPIEZA DE SHARES (idempotencia)
-- ============================================================================
ALTER ACCOUNT SET CORTEX_ENABLED_CROSS_REGION = 'ANY_REGION';
ALTER ACCOUNT SET TIMEZONE = 'America/Bogota';
DROP SHARE IF EXISTS SH_AUDIENCIA_ALTO_VOLUMEN_USER;

-- ============================================================================
-- 1. WAREHOUSE
-- ============================================================================
CREATE WAREHOUSE IF NOT EXISTS CREDIBANCO_HOL_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Warehouse HOL CredibanCo V2';

USE WAREHOUSE CREDIBANCO_HOL_WH;

-- ============================================================================
-- 2. DATABASE + 12 SCHEMAS
-- ============================================================================
CREATE DATABASE IF NOT EXISTS CREDIBANCO_HOL COMMENT = 'Workshop RFP 10010806 - HOL CredibanCo V2';
USE DATABASE CREDIBANCO_HOL;

CREATE SCHEMA IF NOT EXISTS PAGOS         COMMENT = 'Autorizaciones y liquidaciones';
CREATE SCHEMA IF NOT EXISTS COMERCIOS     COMMENT = 'Comercios, terminales, golden record';
CREATE SCHEMA IF NOT EXISTS CLIENTES      COMMENT = 'Tarjetahabientes y productos';
CREATE SCHEMA IF NOT EXISTS RIESGO        COMMENT = 'Red transaccional, contracargos, alertas';
CREATE SCHEMA IF NOT EXISTS TURISMO       COMMENT = 'Agregados monetizables';
CREATE SCHEMA IF NOT EXISTS GOBIERNO      COMMENT = 'Tags, masking, RAP, controles';
CREATE SCHEMA IF NOT EXISTS PLATAFORMA    COMMENT = 'Stage, dbt, DCM, sandbox, FinOps';
CREATE SCHEMA IF NOT EXISTS ANALITICA     COMMENT = 'Anomaly detection, ML, Cortex Search';
CREATE SCHEMA IF NOT EXISTS MONETIZACION  COMMENT = 'Shares, audiencias, semantic views';
CREATE SCHEMA IF NOT EXISTS MIGRACION     COMMENT = 'Reconciliacion Cloudera/Oracle';
CREATE SCHEMA IF NOT EXISTS CUMPLIMIENTO  COMMENT = 'SARLAFT, documentos compliance';
CREATE SCHEMA IF NOT EXISTS ARQUITECTURA  COMMENT = 'Objetos track 3';
CREATE SCHEMA IF NOT EXISTS DCM_ARTIFACTS COMMENT = 'Drift detection track 7';

-- ============================================================================
-- 3. ROLES
-- ============================================================================
CREATE ROLE IF NOT EXISTS CRB_HOL_ADMIN;
CREATE ROLE IF NOT EXISTS CRB_SEGURIDAD_INFO;
CREATE ROLE IF NOT EXISTS CRB_DATA_ANALYTICS;
CREATE ROLE IF NOT EXISTS CRB_ARQUITECTURA;
CREATE ROLE IF NOT EXISTS CRB_ANALITICA;
CREATE ROLE IF NOT EXISTS CRB_NEGOCIO;
CREATE ROLE IF NOT EXISTS CRB_INFRAESTRUCTURA;
CREATE ROLE IF NOT EXISTS CRB_MIGRACION;

GRANT ROLE CRB_HOL_ADMIN TO ROLE SYSADMIN;
GRANT ROLE CRB_SEGURIDAD_INFO TO ROLE CRB_HOL_ADMIN;
GRANT ROLE CRB_DATA_ANALYTICS TO ROLE CRB_HOL_ADMIN;
GRANT ROLE CRB_ARQUITECTURA TO ROLE CRB_HOL_ADMIN;
GRANT ROLE CRB_ANALITICA TO ROLE CRB_HOL_ADMIN;
GRANT ROLE CRB_NEGOCIO TO ROLE CRB_HOL_ADMIN;
GRANT ROLE CRB_INFRAESTRUCTURA TO ROLE CRB_HOL_ADMIN;
GRANT ROLE CRB_MIGRACION TO ROLE CRB_HOL_ADMIN;

-- Grant all roles to USER
GRANT ROLE CRB_HOL_ADMIN TO USER USER;
GRANT ROLE CRB_SEGURIDAD_INFO TO USER USER;
GRANT ROLE CRB_DATA_ANALYTICS TO USER USER;
GRANT ROLE CRB_ARQUITECTURA TO USER USER;
GRANT ROLE CRB_ANALITICA TO USER USER;
GRANT ROLE CRB_NEGOCIO TO USER USER;
GRANT ROLE CRB_INFRAESTRUCTURA TO USER USER;
GRANT ROLE CRB_MIGRACION TO USER USER;

ALTER USER USER SET DEFAULT_WAREHOUSE = CREDIBANCO_HOL_WH;
ALTER USER USER SET DEFAULT_ROLE = CRB_HOL_ADMIN;
ALTER USER USER SET DEFAULT_NAMESPACE = CREDIBANCO_HOL.PAGOS;

-- 5 HOL users + experience user
CREATE USER IF NOT EXISTS CRB_USER_1 PASSWORD = 'Credibanco2026!' DEFAULT_ROLE = CRB_ARQUITECTURA DEFAULT_WAREHOUSE = CREDIBANCO_HOL_WH DEFAULT_NAMESPACE = 'CREDIBANCO_HOL.PAGOS' MUST_CHANGE_PASSWORD = FALSE;
GRANT ROLE CRB_ARQUITECTURA TO USER CRB_USER_1;
GRANT ROLE CRB_SEGURIDAD_INFO TO USER CRB_USER_1;
CREATE USER IF NOT EXISTS CRB_USER_2 PASSWORD = 'Credibanco2026!' DEFAULT_ROLE = CRB_DATA_ANALYTICS DEFAULT_WAREHOUSE = CREDIBANCO_HOL_WH DEFAULT_NAMESPACE = 'CREDIBANCO_HOL.PAGOS' MUST_CHANGE_PASSWORD = FALSE;
GRANT ROLE CRB_DATA_ANALYTICS TO USER CRB_USER_2;
CREATE USER IF NOT EXISTS CRB_USER_3 PASSWORD = 'Credibanco2026!' DEFAULT_ROLE = CRB_ANALITICA DEFAULT_WAREHOUSE = CREDIBANCO_HOL_WH DEFAULT_NAMESPACE = 'CREDIBANCO_HOL.PAGOS' MUST_CHANGE_PASSWORD = FALSE;
GRANT ROLE CRB_ANALITICA TO USER CRB_USER_3;
GRANT ROLE CRB_NEGOCIO TO USER CRB_USER_3;
CREATE USER IF NOT EXISTS CRB_USER_4 PASSWORD = 'Credibanco2026!' DEFAULT_ROLE = CRB_NEGOCIO DEFAULT_WAREHOUSE = CREDIBANCO_HOL_WH DEFAULT_NAMESPACE = 'CREDIBANCO_HOL.PAGOS' MUST_CHANGE_PASSWORD = FALSE;
GRANT ROLE CRB_NEGOCIO TO USER CRB_USER_4;
GRANT ROLE CRB_INFRAESTRUCTURA TO USER CRB_USER_4;
CREATE USER IF NOT EXISTS CRB_USER_5 PASSWORD = 'Credibanco2026!' DEFAULT_ROLE = CRB_MIGRACION DEFAULT_WAREHOUSE = CREDIBANCO_HOL_WH DEFAULT_NAMESPACE = 'CREDIBANCO_HOL.PAGOS' MUST_CHANGE_PASSWORD = FALSE;
GRANT ROLE CRB_MIGRACION TO USER CRB_USER_5;
GRANT ROLE CRB_HOL_ADMIN TO USER CRB_USER_5;
CREATE USER IF NOT EXISTS CRB_EXPERIENCIA PASSWORD = 'Credibanco2026!' DEFAULT_ROLE = CRB_HOL_ADMIN DEFAULT_WAREHOUSE = CREDIBANCO_HOL_WH DEFAULT_NAMESPACE = 'CREDIBANCO_HOL.PAGOS' MUST_CHANGE_PASSWORD = FALSE;
GRANT ROLE CRB_HOL_ADMIN TO USER CRB_EXPERIENCIA;
GRANT ROLE CRB_SEGURIDAD_INFO TO USER CRB_EXPERIENCIA;
GRANT ROLE CRB_DATA_ANALYTICS TO USER CRB_EXPERIENCIA;
GRANT ROLE CRB_ARQUITECTURA TO USER CRB_EXPERIENCIA;
GRANT ROLE CRB_ANALITICA TO USER CRB_EXPERIENCIA;
GRANT ROLE CRB_NEGOCIO TO USER CRB_EXPERIENCIA;
GRANT ROLE CRB_INFRAESTRUCTURA TO USER CRB_EXPERIENCIA;
GRANT ROLE CRB_MIGRACION TO USER CRB_EXPERIENCIA;

-- ============================================================================
-- 4. STAGE FOR DATA LOADING
-- ============================================================================
CREATE STAGE IF NOT EXISTS CREDIBANCO_HOL.PLATAFORMA.STG_HOL_DATA
    ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE')
    COMMENT = 'Stage para carga de datos Parquet del HOL';

CREATE STAGE IF NOT EXISTS CREDIBANCO_HOL.PLATAFORMA.STG_S3_DATOS
    ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE')
    COMMENT = 'Stage interno datos sinteticos HOL CredibanCo';

-- ============================================================================
-- 5. TABLES (DDL only — data loaded via COPY INTO from Parquet)
-- ============================================================================

-- COMERCIOS
CREATE TABLE IF NOT EXISTS CREDIBANCO_HOL.COMERCIOS.COMERCIOS (
    COMERCIO_ID NUMBER PRIMARY KEY, NIT VARCHAR(20), RAZON_SOCIAL VARCHAR(200),
    CIUDAD VARCHAR(100), MCC VARCHAR(10), ORIGEN_REGISTRO VARCHAR(20), FECHA_AFILIACION DATE
);

CREATE TABLE IF NOT EXISTS CREDIBANCO_HOL.COMERCIOS.TERMINALES (
    TERMINAL_ID NUMBER PRIMARY KEY, COMERCIO_ID NUMBER, TIPO VARCHAR(30),
    FECHA_INSTALACION DATE, ESTADO VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS CREDIBANCO_HOL.COMERCIOS.RED_COMERCIOS (
    COMERCIO_ID VARCHAR(20), COMERCIO_RELACIONADO_ID VARCHAR(20), TIPO_RELACION VARCHAR(40)
);

CREATE TABLE IF NOT EXISTS CREDIBANCO_HOL.COMERCIOS.GOLDEN_COMERCIOS (
    NIT VARCHAR(20), COMERCIO_ID_CANONICO NUMBER, RAZON_SOCIAL_CANONICA VARCHAR(200),
    CIUDAD VARCHAR(100), MCC VARCHAR(10), NUM_VARIANTES NUMBER, CONFIANZA FLOAT
);

-- CLIENTES
CREATE TABLE IF NOT EXISTS CREDIBANCO_HOL.CLIENTES.TARJETAHABIENTES (
    TARJETAHABIENTE_ID NUMBER PRIMARY KEY, NOMBRE VARCHAR(150), DOCUMENTO VARCHAR(20),
    CELULAR VARCHAR(20), PAN_SINTETICO VARCHAR(19), FECHA_NACIMIENTO DATE,
    NOMBRE_COMPLETO VARCHAR(150), CORREO VARCHAR(100), NUMERO_DOCUMENTO VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS CREDIBANCO_HOL.CLIENTES.PRODUCTOS (
    PRODUCTO_ID NUMBER PRIMARY KEY, NOMBRE VARCHAR(100), DESCRIPCION VARCHAR(300)
);

-- PAGOS
CREATE TABLE IF NOT EXISTS CREDIBANCO_HOL.PAGOS.AUTORIZACIONES (
    AUTORIZACION_ID NUMBER PRIMARY KEY, COMERCIO_ID NUMBER, TARJETAHABIENTE_ID NUMBER,
    PAN VARCHAR(19), MCC VARCHAR(10), CIUDAD VARCHAR(100), FECHA_HORA TIMESTAMP_NTZ,
    MONTO NUMBER(15,2), CODIGO_RESPUESTA VARCHAR(2), CANAL VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS CREDIBANCO_HOL.PAGOS.LIQUIDACIONES (
    LIQUIDACION_ID NUMBER PRIMARY KEY, AUTORIZACION_ID NUMBER, COMERCIO_ID NUMBER,
    MONTO_LIQUIDADO NUMBER(15,2), FECHA_LIQUIDACION DATE, ESTADO VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS CREDIBANCO_HOL.PAGOS.AUTORIZACIONES_JSON (
    AUTORIZACION_ID NUMBER, METADATA_DISPOSITIVO VARIANT
);

CREATE TABLE IF NOT EXISTS CREDIBANCO_HOL.PAGOS.AUTORIZACIONES_STREAMING (
    AUTORIZACION_ID NUMBER, COMERCIO_ID NUMBER, PAN VARCHAR(19), CIUDAD VARCHAR(50),
    MONTO NUMBER(18,2), CREATETIME NUMBER, OFFSET_PARTITION NUMBER, RECORD_CONTENT VARIANT
);

CREATE TABLE IF NOT EXISTS CREDIBANCO_HOL.PAGOS.AUTORIZACIONES_METADATA_RAW (
    AUTORIZACION_ID NUMBER, METADATA VARIANT
);

-- RIESGO
CREATE TABLE IF NOT EXISTS CREDIBANCO_HOL.RIESGO.RED_TRANSACCIONAL (
    NODO_ORIGEN NUMBER, NODO_DESTINO NUMBER, TIPO_RELACION VARCHAR(40), MONTO_ACUMULADO NUMBER(15,2)
);

CREATE TABLE IF NOT EXISTS CREDIBANCO_HOL.RIESGO.CONTRACARGOS (
    CONTRACARGO_ID NUMBER PRIMARY KEY, AUTORIZACION_ID NUMBER, MOTIVO VARCHAR(200),
    MONTO NUMBER(15,2), FECHA DATE, ESTADO VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS CREDIBANCO_HOL.RIESGO.ALERTAS (
    ALERTA_ID NUMBER PRIMARY KEY, TIPO VARCHAR(40), COMERCIO_ID NUMBER,
    SEVERIDAD VARCHAR(10), FECHA_HORA TIMESTAMP_NTZ, DESCRIPCION VARCHAR(500)
);

-- TURISMO
CREATE TABLE IF NOT EXISTS CREDIBANCO_HOL.TURISMO.AGREGADOS_TURISMO (
    REGION VARCHAR(50), MCC VARCHAR(10), MES DATE, NUM_TRANSACCIONES NUMBER, MONTO_TOTAL NUMBER(18,2)
);

-- GOBIERNO
CREATE TABLE IF NOT EXISTS CREDIBANCO_HOL.GOBIERNO.CATALOGO_CONTROLES (
    CONTROL_ID INT, NOMBRE_CONTROL VARCHAR(100), DESCRIPCION VARCHAR(500),
    TIPO VARCHAR(50), DOMINIO VARCHAR(50), ESTADO VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS CREDIBANCO_HOL.GOBIERNO.CONTRATOS_DATOS (
    CONTRATO_ID INT, PRODUCTO_DATO VARCHAR(100), DOMINIO_PROPIETARIO VARCHAR(50),
    DOMINIO_CONSUMIDOR VARCHAR(50), SLA_FRESCURA VARCHAR(50), SLA_CALIDAD VARCHAR(50),
    RESPONSABLE VARCHAR(100), ESTADO VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS CREDIBANCO_HOL.GOBIERNO.CATALOGO_CASOS_USO (
    CASO_USO_ID INT, NOMBRE VARCHAR(100), DESCRIPCION VARCHAR(500), DOMINIO VARCHAR(50),
    OBJETOS_FUENTE VARIANT, AREA_NEGOCIO VARCHAR(50), ESTADO VARCHAR(20)
);

-- ANALITICA
CREATE TABLE IF NOT EXISTS CREDIBANCO_HOL.ANALITICA.TRAIN_ANOMALIAS (
    COMERCIO_ID NUMBER, FECHA DATE, MONTO_TOTAL NUMBER(15,2)
);

CREATE TABLE IF NOT EXISTS CREDIBANCO_HOL.ANALITICA.TRAIN_RIESGO_COMERCIO (
    COMERCIO_ID NUMBER, NUM_AUTORIZACIONES NUMBER, TICKET_PROMEDIO FLOAT,
    DESVIACION_MONTO FLOAT, TASA_RECHAZO FLOAT, NUM_CIUDADES NUMBER,
    EN_ANILLO_SOSPECHOSO NUMBER, ES_FRAUDE NUMBER
);

CREATE TABLE IF NOT EXISTS CREDIBANCO_HOL.ANALITICA.RESULTADO_ANOMALIAS (
    COMERCIO_ID NUMBER, FECHA DATE, MONTO_TOTAL NUMBER(15,2), IS_ANOMALY BOOLEAN,
    PERCENTILE FLOAT, DISTANCE FLOAT, FORECAST FLOAT
);

CREATE TABLE IF NOT EXISTS CREDIBANCO_HOL.ANALITICA.FEATURES_RIESGO_COMERCIO (
    COMERCIO_ID NUMBER, NUM_AUTORIZACIONES NUMBER, TICKET_PROMEDIO FLOAT,
    TASA_RECHAZO FLOAT, NUM_CIUDADES NUMBER, EN_ANILLO_SOSPECHOSO NUMBER
);

-- CUMPLIMIENTO
CREATE TABLE IF NOT EXISTS CREDIBANCO_HOL.CUMPLIMIENTO.DOCUMENTOS_SARLAFT (
    DOCUMENTO_ID INT, TIPO_ALERTA VARCHAR(50), TEXTO_DOCUMENTO VARCHAR(2000)
);

CREATE TABLE IF NOT EXISTS CREDIBANCO_HOL.ANALITICA.ALERTAS_RIESGO (
    ALERTA_ID INT, COMERCIO_ID VARCHAR(20), DESCRIPCION_ALERTA VARCHAR(1000)
);

-- MIGRACION
CREATE TABLE IF NOT EXISTS CREDIBANCO_HOL.MIGRACION.EQUIVALENCIAS_SQL (
    ID INT, PLATAFORMA_ORIGEN VARCHAR(50), SENTENCIA_ORIGEN VARCHAR(1000),
    SENTENCIA_SNOWFLAKE VARCHAR(1000), CATEGORIA VARCHAR(50), NOTAS VARCHAR(500)
);

CREATE TABLE IF NOT EXISTS CREDIBANCO_HOL.MIGRACION.RECONCILIACION_DIARIA (
    FECHA DATE, ESTADO VARCHAR(20), DETALLE VARCHAR(500), REGISTRADO_EN TIMESTAMP_NTZ
);

-- PLATAFORMA
CREATE TABLE IF NOT EXISTS CREDIBANCO_HOL.PLATAFORMA.CONFIG_DATAOPS (
    CLAVE VARCHAR(100), VALOR VARCHAR(500), ACTUALIZADO_POR VARCHAR(50), FECHA TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS CREDIBANCO_HOL.PLATAFORMA.METADATA_DISPOSITIVOS (
    AUTORIZACION_ID NUMBER, PAYLOAD VARIANT
);

-- ============================================================================
-- 6. TAGS
-- ============================================================================
CREATE TAG IF NOT EXISTS CREDIBANCO_HOL.GOBIERNO.TAG_PII ALLOWED_VALUES 'nombre','correo','documento','celular';
CREATE TAG IF NOT EXISTS CREDIBANCO_HOL.GOBIERNO.TAG_PAN ALLOWED_VALUES 'pan';
CREATE TAG IF NOT EXISTS CREDIBANCO_HOL.GOBIERNO.TAG_CONFIDENCIAL ALLOWED_VALUES 'monto','nit','limite_credito';
CREATE TAG IF NOT EXISTS CREDIBANCO_HOL.GOBIERNO.TAG_CONFIDENCIALIDAD ALLOWED_VALUES 'publica','interna','confidencial','restringida';
CREATE TAG IF NOT EXISTS CREDIBANCO_HOL.GOBIERNO.TAG_DOMINIO ALLOWED_VALUES 'PAGOS','COMERCIOS','CLIENTES','RIESGO','TURISMO','PLATAFORMA','GOBIERNO','ANALITICA','MIGRACION';
CREATE TAG IF NOT EXISTS CREDIBANCO_HOL.GOBIERNO.DOMINIO_NEGOCIO ALLOWED_VALUES 'Comercios','Pagos','Riesgo','Clientes','Plataforma';
CREATE TAG IF NOT EXISTS CREDIBANCO_HOL.GOBIERNO.CASO_USO ALLOWED_VALUES 'Deteccion fraude','MDM comercios','Liquidaciones','Analisis riesgo','Reportes regulatorios';
CREATE TAG IF NOT EXISTS CREDIBANCO_HOL.GOBIERNO.TAG_OWNER COMMENT = 'Equipo propietario del objeto';

-- ============================================================================
-- 7. MASKING POLICIES (Track 1)
-- ============================================================================
CREATE OR REPLACE MASKING POLICY CREDIBANCO_HOL.GOBIERNO.MASK_PAN
  AS (val STRING) RETURNS STRING ->
  CASE WHEN CURRENT_ROLE() IN ('CRB_SEGURIDAD_INFO','CRB_HOL_ADMIN','ACCOUNTADMIN') THEN val
       ELSE 'TOKEN-' || SHA2(val, 256) END;

CREATE OR REPLACE MASKING POLICY CREDIBANCO_HOL.GOBIERNO.MASK_CEDULA
  AS (val STRING) RETURNS STRING ->
  CASE WHEN CURRENT_ROLE() IN ('CRB_SEGURIDAD_INFO','CRB_HOL_ADMIN','ACCOUNTADMIN') THEN val
       ELSE '***' END;

CREATE OR REPLACE MASKING POLICY CREDIBANCO_HOL.GOBIERNO.MASK_CELULAR
  AS (val STRING) RETURNS STRING ->
  CASE WHEN CURRENT_ROLE() IN ('CRB_SEGURIDAD_INFO','CRB_HOL_ADMIN','ACCOUNTADMIN') THEN val
       ELSE SUBSTR(val,1,3)||'*****'||SUBSTR(val,9,2) END;

-- Apply masking policies to columns
ALTER TABLE IF EXISTS CREDIBANCO_HOL.CLIENTES.TARJETAHABIENTES MODIFY COLUMN PAN_SINTETICO SET MASKING POLICY CREDIBANCO_HOL.GOBIERNO.MASK_PAN FORCE;
ALTER TABLE IF EXISTS CREDIBANCO_HOL.CLIENTES.TARJETAHABIENTES MODIFY COLUMN DOCUMENTO SET MASKING POLICY CREDIBANCO_HOL.GOBIERNO.MASK_CEDULA FORCE;
ALTER TABLE IF EXISTS CREDIBANCO_HOL.CLIENTES.TARJETAHABIENTES MODIFY COLUMN CELULAR SET MASKING POLICY CREDIBANCO_HOL.GOBIERNO.MASK_CELULAR FORCE;

-- Apply PII tags to sensitive columns
ALTER TABLE IF EXISTS CREDIBANCO_HOL.CLIENTES.TARJETAHABIENTES MODIFY COLUMN PAN_SINTETICO SET TAG CREDIBANCO_HOL.GOBIERNO.TAG_PII = 'documento';
ALTER TABLE IF EXISTS CREDIBANCO_HOL.CLIENTES.TARJETAHABIENTES MODIFY COLUMN DOCUMENTO SET TAG CREDIBANCO_HOL.GOBIERNO.TAG_PII = 'documento';
ALTER TABLE IF EXISTS CREDIBANCO_HOL.CLIENTES.TARJETAHABIENTES MODIFY COLUMN CELULAR SET TAG CREDIBANCO_HOL.GOBIERNO.TAG_PII = 'celular';
ALTER TABLE IF EXISTS CREDIBANCO_HOL.CLIENTES.TARJETAHABIENTES MODIFY COLUMN CORREO SET TAG CREDIBANCO_HOL.GOBIERNO.TAG_PII = 'correo';
ALTER TABLE IF EXISTS CREDIBANCO_HOL.CLIENTES.TARJETAHABIENTES MODIFY COLUMN NOMBRE SET TAG CREDIBANCO_HOL.GOBIERNO.TAG_PII = 'nombre';

-- Database Roles (for T0 Arquitectura)
CREATE DATABASE ROLE IF NOT EXISTS CREDIBANCO_HOL.DR_PAGOS;
CREATE DATABASE ROLE IF NOT EXISTS CREDIBANCO_HOL.DR_COMERCIOS;
CREATE DATABASE ROLE IF NOT EXISTS CREDIBANCO_HOL.DR_CLIENTES;
CREATE DATABASE ROLE IF NOT EXISTS CREDIBANCO_HOL.DR_CUMPLIMIENTO;
CREATE DATABASE ROLE IF NOT EXISTS CREDIBANCO_HOL.DR_GOBIERNO;
GRANT USAGE ON SCHEMA CREDIBANCO_HOL.PAGOS TO DATABASE ROLE CREDIBANCO_HOL.DR_PAGOS;
GRANT USAGE ON SCHEMA CREDIBANCO_HOL.COMERCIOS TO DATABASE ROLE CREDIBANCO_HOL.DR_COMERCIOS;
GRANT USAGE ON SCHEMA CREDIBANCO_HOL.CLIENTES TO DATABASE ROLE CREDIBANCO_HOL.DR_CLIENTES;
GRANT USAGE ON SCHEMA CREDIBANCO_HOL.CUMPLIMIENTO TO DATABASE ROLE CREDIBANCO_HOL.DR_CUMPLIMIENTO;
GRANT USAGE ON SCHEMA CREDIBANCO_HOL.GOBIERNO TO DATABASE ROLE CREDIBANCO_HOL.DR_GOBIERNO;

-- Network Rule + EAI for API ingestion (T2)
CREATE OR REPLACE NETWORK RULE CREDIBANCO_HOL.PLATAFORMA.NR_DATOS_GOV
  MODE = EGRESS TYPE = HOST_PORT VALUE_LIST = ('www.datos.gov.co:443');
CREATE OR REPLACE EXTERNAL ACCESS INTEGRATION EAI_DATOS_GOV
  ALLOWED_NETWORK_RULES = (CREDIBANCO_HOL.PLATAFORMA.NR_DATOS_GOV)
  ENABLED = TRUE;

-- ============================================================================
-- 8. ROW ACCESS POLICY (Track 1) — idempotent: detach before replace
-- ============================================================================
ALTER TABLE IF EXISTS CREDIBANCO_HOL.PAGOS.AUTORIZACIONES DROP ALL ROW ACCESS POLICIES;
CREATE OR REPLACE ROW ACCESS POLICY CREDIBANCO_HOL.GOBIERNO.RAP_AUTORIZACIONES
  AS (codigo STRING) RETURNS BOOLEAN ->
  CURRENT_ROLE() IN ('CRB_SEGURIDAD_INFO','CRB_DATA_ANALYTICS','CRB_ARQUITECTURA',
    'CRB_ANALITICA','CRB_INFRAESTRUCTURA','CRB_NEGOCIO','CRB_MIGRACION',
    'CRB_HOL_ADMIN','ACCOUNTADMIN');

-- ============================================================================
-- 9. NETWORK RULE + AUTH POLICY (Track 1)
-- ============================================================================
CREATE OR REPLACE NETWORK RULE CREDIBANCO_HOL.GOBIERNO.NETRULE_HOL_DEMO
  TYPE = IPV4 MODE = INGRESS VALUE_LIST = ('0.0.0.0/0')
  COMMENT = 'Regla de red HOL CredibanCo';

CREATE OR REPLACE AUTHENTICATION POLICY CREDIBANCO_HOL.GOBIERNO.POLICY_AUTENTICACION_CRB
  AUTHENTICATION_METHODS = ('PASSWORD', 'SAML')
  MFA_ENROLLMENT = 'OPTIONAL'
  CLIENT_TYPES = ('SNOWFLAKE_UI', 'SNOWSQL')
  COMMENT = 'Politica de autenticacion HOL CredibanCo';

-- ============================================================================
-- 10. VIEWS (Track 4)
-- ============================================================================
CREATE OR REPLACE VIEW CREDIBANCO_HOL.ANALITICA.V_SERIE_MONTOS_ENTRENAMIENTO AS
SELECT comercio_id, fecha_hora::DATE AS fecha, SUM(monto) AS monto_total
FROM CREDIBANCO_HOL.PAGOS.AUTORIZACIONES
WHERE fecha_hora::DATE < DATEADD('day', -30, CURRENT_DATE())
GROUP BY comercio_id, fecha_hora::DATE;

CREATE OR REPLACE VIEW CREDIBANCO_HOL.ANALITICA.V_SERIE_MONTOS_PRUEBA AS
SELECT comercio_id, fecha_hora::DATE AS fecha, SUM(monto) AS monto_total
FROM CREDIBANCO_HOL.PAGOS.AUTORIZACIONES
WHERE fecha_hora::DATE >= DATEADD('day', -30, CURRENT_DATE())
GROUP BY comercio_id, fecha_hora::DATE;

-- Track 6 secure view
CREATE OR REPLACE SECURE VIEW CREDIBANCO_HOL.MONETIZACION.AUD_ALTO_VOLUMEN AS
SELECT comercio_id, ciudad, mcc, COUNT(*) AS num_transacciones, SUM(monto) AS monto_total
FROM CREDIBANCO_HOL.PAGOS.AUTORIZACIONES
GROUP BY comercio_id, ciudad, mcc
HAVING COUNT(*) > 5;

-- Track 7 view
CREATE OR REPLACE VIEW CREDIBANCO_HOL.PLATAFORMA.SV_CONSUMO_HOL
  COMMENT = 'Vista analitica de consumo para el Agente FinOps' AS
SELECT WAREHOUSE_NAME, CREDITS_USED, START_TIME::DATE AS FECHA, START_TIME::TIME AS HORA
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
WHERE START_TIME >= DATEADD(day, -30, CURRENT_TIMESTAMP());

-- ============================================================================
-- 11. PROCEDURES
-- ============================================================================
CREATE OR REPLACE PROCEDURE CREDIBANCO_HOL.MIGRACION.RECONCILIAR_DIA(p_fecha DATE)
RETURNS VARCHAR LANGUAGE SQL AS
$$
DECLARE v_count NUMBER; v_sum NUMBER;
BEGIN
    v_count := (SELECT COUNT(*) FROM CREDIBANCO_HOL.PAGOS.AUTORIZACIONES WHERE fecha_hora::DATE = :p_fecha);
    v_sum := (SELECT COALESCE(SUM(monto),0) FROM CREDIBANCO_HOL.PAGOS.AUTORIZACIONES WHERE fecha_hora::DATE = :p_fecha);
    INSERT INTO CREDIBANCO_HOL.MIGRACION.RECONCILIACION_DIARIA VALUES (:p_fecha, 'OK', 'Conteo=' || :v_count || ', suma=' || :v_sum, CURRENT_TIMESTAMP());
    RETURN 'OK: fecha=' || :p_fecha || ' conteo=' || :v_count || ' suma=' || :v_sum;
END;
$$;

CREATE OR REPLACE PROCEDURE CREDIBANCO_HOL.PLATAFORMA.SOLICITAR_SANDBOX(p_nombre VARCHAR, p_dias NUMBER)
RETURNS VARCHAR LANGUAGE SQL AS
$$
BEGIN
    RETURN 'OK: SANDBOX_' || UPPER(REPLACE(:p_nombre,' ','_'));
END;
$$;

CREATE OR REPLACE FUNCTION CREDIBANCO_HOL.PLATAFORMA.CONSUMO_POR_SERVICIO(dias_atras NUMBER)
  RETURNS TABLE (SERVICE_TYPE VARCHAR, TOTAL_CREDITS FLOAT) AS $$
    SELECT SERVICE_TYPE, SUM(CREDITS_USED)::FLOAT AS TOTAL_CREDITS
    FROM SNOWFLAKE.ACCOUNT_USAGE.METERING_HISTORY
    WHERE START_TIME >= DATEADD(day, -dias_atras, CURRENT_TIMESTAMP())
    GROUP BY 1 ORDER BY 2 DESC
  $$;

-- ============================================================================
-- 12. DMF (Data Metric Function)
-- ============================================================================
CREATE OR REPLACE DATA METRIC FUNCTION CREDIBANCO_HOL.GOBIERNO.DMF_MONTO_VALIDO(
    ARG_T TABLE(monto NUMBER)) RETURNS NUMBER AS
'SELECT COUNT_IF(monto IS NULL OR monto < 0 OR monto > 50000000) FROM ARG_T';

-- ============================================================================
-- 13. STAGE for migration scripts (Track 8)
-- ============================================================================
CREATE STAGE IF NOT EXISTS CREDIBANCO_HOL.MIGRACION.STG_MIGRATION_FILES
  COMMENT = 'Scripts HiveQL, Spark, SQL para conversion con SnowConvert';

-- ============================================================================
-- 14. RESOURCE MONITOR
-- ============================================================================
CREATE OR REPLACE RESOURCE MONITOR RM_HOL_CREDIBANCO
  WITH CREDIT_QUOTA = 100
  TRIGGERS ON 75 PERCENT DO NOTIFY ON 90 PERCENT DO NOTIFY ON 100 PERCENT DO SUSPEND;

-- ============================================================================
-- 15. CHANGE TRACKING (needed for Dynamic Tables in Track 2)
-- ============================================================================
ALTER TABLE CREDIBANCO_HOL.PAGOS.AUTORIZACIONES SET CHANGE_TRACKING = TRUE;

-- ============================================================================
-- 16. GRANTS — COMPREHENSIVE
-- ============================================================================

-- CRB_HOL_ADMIN: owner of all schemas
GRANT ALL ON DATABASE CREDIBANCO_HOL TO ROLE CRB_HOL_ADMIN;
GRANT ALL ON ALL SCHEMAS IN DATABASE CREDIBANCO_HOL TO ROLE CRB_HOL_ADMIN;
GRANT USAGE, OPERATE, MODIFY ON WAREHOUSE CREDIBANCO_HOL_WH TO ROLE CRB_HOL_ADMIN;

-- Cortex for ALL
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE PUBLIC;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE CRB_SEGURIDAD_INFO;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE CRB_DATA_ANALYTICS;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE CRB_ARQUITECTURA;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE CRB_ANALITICA;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE CRB_NEGOCIO;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE CRB_INFRAESTRUCTURA;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE CRB_MIGRACION;

-- CRB_SEGURIDAD_INFO (Track 1)
GRANT USAGE ON DATABASE CREDIBANCO_HOL TO ROLE CRB_SEGURIDAD_INFO;
GRANT USAGE ON WAREHOUSE CREDIBANCO_HOL_WH TO ROLE CRB_SEGURIDAD_INFO;
GRANT ALL ON SCHEMA CREDIBANCO_HOL.GOBIERNO TO ROLE CRB_SEGURIDAD_INFO;
GRANT USAGE ON SCHEMA CREDIBANCO_HOL.PAGOS TO ROLE CRB_SEGURIDAD_INFO;
GRANT USAGE ON SCHEMA CREDIBANCO_HOL.CLIENTES TO ROLE CRB_SEGURIDAD_INFO;
GRANT USAGE ON SCHEMA CREDIBANCO_HOL.COMERCIOS TO ROLE CRB_SEGURIDAD_INFO;
GRANT USAGE ON SCHEMA CREDIBANCO_HOL.PLATAFORMA TO ROLE CRB_SEGURIDAD_INFO;
GRANT SELECT ON ALL TABLES IN SCHEMA CREDIBANCO_HOL.PAGOS TO ROLE CRB_SEGURIDAD_INFO;
GRANT SELECT ON ALL TABLES IN SCHEMA CREDIBANCO_HOL.CLIENTES TO ROLE CRB_SEGURIDAD_INFO;
GRANT SELECT ON ALL TABLES IN SCHEMA CREDIBANCO_HOL.COMERCIOS TO ROLE CRB_SEGURIDAD_INFO;
GRANT SELECT ON FUTURE TABLES IN SCHEMA CREDIBANCO_HOL.PAGOS TO ROLE CRB_SEGURIDAD_INFO;
GRANT SELECT ON FUTURE TABLES IN SCHEMA CREDIBANCO_HOL.CLIENTES TO ROLE CRB_SEGURIDAD_INFO;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA CREDIBANCO_HOL.GOBIERNO TO ROLE CRB_SEGURIDAD_INFO;
GRANT CREATE TABLE ON SCHEMA CREDIBANCO_HOL.GOBIERNO TO ROLE CRB_SEGURIDAD_INFO;
GRANT CREATE MASKING POLICY ON SCHEMA CREDIBANCO_HOL.GOBIERNO TO ROLE CRB_SEGURIDAD_INFO;
GRANT CREATE ROW ACCESS POLICY ON SCHEMA CREDIBANCO_HOL.GOBIERNO TO ROLE CRB_SEGURIDAD_INFO;
GRANT CREATE TAG ON SCHEMA CREDIBANCO_HOL.GOBIERNO TO ROLE CRB_SEGURIDAD_INFO;
GRANT CREATE NETWORK RULE ON SCHEMA CREDIBANCO_HOL.GOBIERNO TO ROLE CRB_SEGURIDAD_INFO;
GRANT CREATE CORTEX SEARCH SERVICE ON SCHEMA CREDIBANCO_HOL.GOBIERNO TO ROLE CRB_SEGURIDAD_INFO;
GRANT CREATE AGENT ON SCHEMA CREDIBANCO_HOL.GOBIERNO TO ROLE CRB_SEGURIDAD_INFO;
GRANT CREATE SEMANTIC VIEW ON SCHEMA CREDIBANCO_HOL.GOBIERNO TO ROLE CRB_SEGURIDAD_INFO;
GRANT CREATE SNOWFLAKE.DATA_PRIVACY.CUSTOM_CLASSIFIER ON SCHEMA CREDIBANCO_HOL.GOBIERNO TO ROLE CRB_SEGURIDAD_INFO;
GRANT APPLY MASKING POLICY ON ACCOUNT TO ROLE CRB_SEGURIDAD_INFO;
GRANT APPLY ROW ACCESS POLICY ON ACCOUNT TO ROLE CRB_SEGURIDAD_INFO;
GRANT APPLY TAG ON ACCOUNT TO ROLE CRB_SEGURIDAD_INFO;

-- CRB_DATA_ANALYTICS (Track 2)
GRANT USAGE ON DATABASE CREDIBANCO_HOL TO ROLE CRB_DATA_ANALYTICS;
GRANT USAGE ON WAREHOUSE CREDIBANCO_HOL_WH TO ROLE CRB_DATA_ANALYTICS;
GRANT ALL ON SCHEMA CREDIBANCO_HOL.PAGOS TO ROLE CRB_DATA_ANALYTICS;
GRANT USAGE ON SCHEMA CREDIBANCO_HOL.PLATAFORMA TO ROLE CRB_DATA_ANALYTICS;
GRANT USAGE ON SCHEMA CREDIBANCO_HOL.COMERCIOS TO ROLE CRB_DATA_ANALYTICS;
GRANT USAGE ON SCHEMA CREDIBANCO_HOL.CLIENTES TO ROLE CRB_DATA_ANALYTICS;
GRANT SELECT ON ALL TABLES IN SCHEMA CREDIBANCO_HOL.COMERCIOS TO ROLE CRB_DATA_ANALYTICS;
GRANT SELECT ON ALL TABLES IN SCHEMA CREDIBANCO_HOL.CLIENTES TO ROLE CRB_DATA_ANALYTICS;
GRANT SELECT, INSERT ON ALL TABLES IN SCHEMA CREDIBANCO_HOL.PAGOS TO ROLE CRB_DATA_ANALYTICS;
GRANT SELECT ON FUTURE TABLES IN SCHEMA CREDIBANCO_HOL.COMERCIOS TO ROLE CRB_DATA_ANALYTICS;
GRANT SELECT ON FUTURE TABLES IN SCHEMA CREDIBANCO_HOL.PAGOS TO ROLE CRB_DATA_ANALYTICS;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA CREDIBANCO_HOL.PAGOS TO ROLE CRB_DATA_ANALYTICS;
GRANT MONITOR ON FUTURE DYNAMIC TABLES IN SCHEMA CREDIBANCO_HOL.PAGOS TO ROLE CRB_DATA_ANALYTICS;
GRANT CREATE TABLE ON SCHEMA CREDIBANCO_HOL.PAGOS TO ROLE CRB_DATA_ANALYTICS;
GRANT CREATE DYNAMIC TABLE ON SCHEMA CREDIBANCO_HOL.PAGOS TO ROLE CRB_DATA_ANALYTICS;
GRANT CREATE VIEW ON SCHEMA CREDIBANCO_HOL.PAGOS TO ROLE CRB_DATA_ANALYTICS;
GRANT CREATE STREAM ON SCHEMA CREDIBANCO_HOL.PAGOS TO ROLE CRB_DATA_ANALYTICS;
GRANT CREATE STREAMLIT ON SCHEMA CREDIBANCO_HOL.PAGOS TO ROLE CRB_DATA_ANALYTICS;
GRANT CREATE PIPE ON SCHEMA CREDIBANCO_HOL.PAGOS TO ROLE CRB_DATA_ANALYTICS;
GRANT CREATE STAGE, CREATE PIPE ON SCHEMA CREDIBANCO_HOL.PLATAFORMA TO ROLE CRB_DATA_ANALYTICS;
GRANT READ, WRITE ON STAGE CREDIBANCO_HOL.PLATAFORMA.STG_S3_DATOS TO ROLE CRB_DATA_ANALYTICS;
GRANT READ, WRITE ON STAGE CREDIBANCO_HOL.PLATAFORMA.STG_HOL_DATA TO ROLE CRB_DATA_ANALYTICS;

-- CRB_ARQUITECTURA (Track 3)
GRANT USAGE ON DATABASE CREDIBANCO_HOL TO ROLE CRB_ARQUITECTURA;
GRANT USAGE ON WAREHOUSE CREDIBANCO_HOL_WH TO ROLE CRB_ARQUITECTURA;
GRANT ALL ON SCHEMA CREDIBANCO_HOL.COMERCIOS TO ROLE CRB_ARQUITECTURA;
GRANT USAGE ON SCHEMA CREDIBANCO_HOL.PLATAFORMA TO ROLE CRB_ARQUITECTURA;
GRANT USAGE ON SCHEMA CREDIBANCO_HOL.PAGOS TO ROLE CRB_ARQUITECTURA;
GRANT USAGE ON SCHEMA CREDIBANCO_HOL.CLIENTES TO ROLE CRB_ARQUITECTURA;
GRANT USAGE ON SCHEMA CREDIBANCO_HOL.RIESGO TO ROLE CRB_ARQUITECTURA;
GRANT USAGE ON SCHEMA CREDIBANCO_HOL.MONETIZACION TO ROLE CRB_ARQUITECTURA;
GRANT USAGE ON SCHEMA CREDIBANCO_HOL.GOBIERNO TO ROLE CRB_ARQUITECTURA;
GRANT USAGE ON SCHEMA CREDIBANCO_HOL.ARQUITECTURA TO ROLE CRB_ARQUITECTURA;
GRANT SELECT ON ALL TABLES IN SCHEMA CREDIBANCO_HOL.PAGOS TO ROLE CRB_ARQUITECTURA;
GRANT SELECT ON ALL TABLES IN SCHEMA CREDIBANCO_HOL.CLIENTES TO ROLE CRB_ARQUITECTURA;
GRANT SELECT ON ALL TABLES IN SCHEMA CREDIBANCO_HOL.RIESGO TO ROLE CRB_ARQUITECTURA;
GRANT SELECT ON ALL TABLES IN SCHEMA CREDIBANCO_HOL.COMERCIOS TO ROLE CRB_ARQUITECTURA;
GRANT SELECT, INSERT ON ALL TABLES IN SCHEMA CREDIBANCO_HOL.GOBIERNO TO ROLE CRB_ARQUITECTURA;
GRANT SELECT ON FUTURE TABLES IN SCHEMA CREDIBANCO_HOL.PAGOS TO ROLE CRB_ARQUITECTURA;
GRANT SELECT ON FUTURE TABLES IN SCHEMA CREDIBANCO_HOL.CLIENTES TO ROLE CRB_ARQUITECTURA;
GRANT CREATE TABLE, CREATE VIEW, CREATE DYNAMIC TABLE ON SCHEMA CREDIBANCO_HOL.COMERCIOS TO ROLE CRB_ARQUITECTURA;
GRANT CREATE TABLE ON SCHEMA CREDIBANCO_HOL.GOBIERNO TO ROLE CRB_ARQUITECTURA;
GRANT CREATE TABLE ON SCHEMA CREDIBANCO_HOL.ARQUITECTURA TO ROLE CRB_ARQUITECTURA;
GRANT CREATE TAG ON SCHEMA CREDIBANCO_HOL.GOBIERNO TO ROLE CRB_ARQUITECTURA;
GRANT CREATE DATA METRIC FUNCTION ON SCHEMA CREDIBANCO_HOL.GOBIERNO TO ROLE CRB_ARQUITECTURA;
GRANT CREATE ALERT ON SCHEMA CREDIBANCO_HOL.GOBIERNO TO ROLE CRB_ARQUITECTURA;
GRANT CREATE CORTEX SEARCH SERVICE ON SCHEMA CREDIBANCO_HOL.GOBIERNO TO ROLE CRB_ARQUITECTURA;
GRANT CREATE DATABASE ROLE ON DATABASE CREDIBANCO_HOL TO ROLE CRB_ARQUITECTURA;
GRANT APPLY TAG ON ACCOUNT TO ROLE CRB_ARQUITECTURA;

-- CRB_ANALITICA (Track 4)
GRANT USAGE ON DATABASE CREDIBANCO_HOL TO ROLE CRB_ANALITICA;
GRANT USAGE ON WAREHOUSE CREDIBANCO_HOL_WH TO ROLE CRB_ANALITICA;
GRANT ALL ON SCHEMA CREDIBANCO_HOL.ANALITICA TO ROLE CRB_ANALITICA;
GRANT USAGE ON SCHEMA CREDIBANCO_HOL.CUMPLIMIENTO TO ROLE CRB_ANALITICA;
GRANT USAGE ON SCHEMA CREDIBANCO_HOL.COMERCIOS TO ROLE CRB_ANALITICA;
GRANT USAGE ON SCHEMA CREDIBANCO_HOL.PAGOS TO ROLE CRB_ANALITICA;
GRANT USAGE ON SCHEMA CREDIBANCO_HOL.CLIENTES TO ROLE CRB_ANALITICA;
GRANT USAGE ON SCHEMA CREDIBANCO_HOL.RIESGO TO ROLE CRB_ANALITICA;
GRANT SELECT ON ALL TABLES IN SCHEMA CREDIBANCO_HOL.PAGOS TO ROLE CRB_ANALITICA;
GRANT SELECT ON ALL TABLES IN SCHEMA CREDIBANCO_HOL.COMERCIOS TO ROLE CRB_ANALITICA;
GRANT SELECT ON ALL TABLES IN SCHEMA CREDIBANCO_HOL.ANALITICA TO ROLE CRB_ANALITICA;
GRANT SELECT ON ALL VIEWS IN SCHEMA CREDIBANCO_HOL.ANALITICA TO ROLE CRB_ANALITICA;
GRANT SELECT ON ALL TABLES IN SCHEMA CREDIBANCO_HOL.CUMPLIMIENTO TO ROLE CRB_ANALITICA;
GRANT SELECT ON FUTURE TABLES IN SCHEMA CREDIBANCO_HOL.PAGOS TO ROLE CRB_ANALITICA;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA CREDIBANCO_HOL.ANALITICA TO ROLE CRB_ANALITICA;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA CREDIBANCO_HOL.CUMPLIMIENTO TO ROLE CRB_ANALITICA;
GRANT CREATE SNOWFLAKE.ML.ANOMALY_DETECTION ON SCHEMA CREDIBANCO_HOL.ANALITICA TO ROLE CRB_ANALITICA;
GRANT CREATE SNOWFLAKE.ML.CLASSIFICATION ON SCHEMA CREDIBANCO_HOL.ANALITICA TO ROLE CRB_ANALITICA;
GRANT CREATE CORTEX SEARCH SERVICE ON SCHEMA CREDIBANCO_HOL.CUMPLIMIENTO TO ROLE CRB_ANALITICA;
GRANT CREATE CORTEX SEARCH SERVICE ON SCHEMA CREDIBANCO_HOL.ANALITICA TO ROLE CRB_ANALITICA;
GRANT CREATE MASKING POLICY ON SCHEMA CREDIBANCO_HOL.ANALITICA TO ROLE CRB_ANALITICA;

-- CRB_NEGOCIO (Tracks 5-6)
GRANT USAGE ON DATABASE CREDIBANCO_HOL TO ROLE CRB_NEGOCIO;
GRANT USAGE ON WAREHOUSE CREDIBANCO_HOL_WH TO ROLE CRB_NEGOCIO;
GRANT ALL ON SCHEMA CREDIBANCO_HOL.MONETIZACION TO ROLE CRB_NEGOCIO;
GRANT ALL ON SCHEMA CREDIBANCO_HOL.TURISMO TO ROLE CRB_NEGOCIO;
GRANT USAGE ON SCHEMA CREDIBANCO_HOL.PLATAFORMA TO ROLE CRB_NEGOCIO;
GRANT USAGE ON SCHEMA CREDIBANCO_HOL.PAGOS TO ROLE CRB_NEGOCIO;
GRANT USAGE ON SCHEMA CREDIBANCO_HOL.COMERCIOS TO ROLE CRB_NEGOCIO;
GRANT USAGE ON SCHEMA CREDIBANCO_HOL.ANALITICA TO ROLE CRB_NEGOCIO;
GRANT SELECT ON ALL TABLES IN SCHEMA CREDIBANCO_HOL.PAGOS TO ROLE CRB_NEGOCIO;
GRANT SELECT ON ALL TABLES IN SCHEMA CREDIBANCO_HOL.COMERCIOS TO ROLE CRB_NEGOCIO;
GRANT SELECT ON ALL TABLES IN SCHEMA CREDIBANCO_HOL.ANALITICA TO ROLE CRB_NEGOCIO;
GRANT SELECT ON ALL VIEWS IN SCHEMA CREDIBANCO_HOL.MONETIZACION TO ROLE CRB_NEGOCIO;
GRANT SELECT ON FUTURE TABLES IN SCHEMA CREDIBANCO_HOL.PAGOS TO ROLE CRB_NEGOCIO;
GRANT CREATE VIEW, CREATE SEMANTIC VIEW ON SCHEMA CREDIBANCO_HOL.MONETIZACION TO ROLE CRB_NEGOCIO;
GRANT CREATE PROCEDURE ON SCHEMA CREDIBANCO_HOL.PLATAFORMA TO ROLE CRB_NEGOCIO;
GRANT CREATE SCHEMA ON DATABASE CREDIBANCO_HOL TO ROLE CRB_NEGOCIO;
GRANT CREATE SHARE ON ACCOUNT TO ROLE CRB_NEGOCIO;

-- CRB_INFRAESTRUCTURA (Track 7)
GRANT USAGE ON DATABASE CREDIBANCO_HOL TO ROLE CRB_INFRAESTRUCTURA;
GRANT USAGE ON WAREHOUSE CREDIBANCO_HOL_WH TO ROLE CRB_INFRAESTRUCTURA;
GRANT MONITOR ON WAREHOUSE CREDIBANCO_HOL_WH TO ROLE CRB_INFRAESTRUCTURA;
GRANT ALL ON SCHEMA CREDIBANCO_HOL.PLATAFORMA TO ROLE CRB_INFRAESTRUCTURA;
GRANT USAGE ON SCHEMA CREDIBANCO_HOL.PAGOS TO ROLE CRB_INFRAESTRUCTURA;
GRANT USAGE ON SCHEMA CREDIBANCO_HOL.COMERCIOS TO ROLE CRB_INFRAESTRUCTURA;
GRANT USAGE ON SCHEMA CREDIBANCO_HOL.CLIENTES TO ROLE CRB_INFRAESTRUCTURA;
GRANT USAGE ON SCHEMA CREDIBANCO_HOL.GOBIERNO TO ROLE CRB_INFRAESTRUCTURA;
GRANT USAGE ON SCHEMA CREDIBANCO_HOL.DCM_ARTIFACTS TO ROLE CRB_INFRAESTRUCTURA;
GRANT SELECT ON ALL TABLES IN SCHEMA CREDIBANCO_HOL.PAGOS TO ROLE CRB_INFRAESTRUCTURA;
GRANT SELECT ON FUTURE TABLES IN SCHEMA CREDIBANCO_HOL.PAGOS TO ROLE CRB_INFRAESTRUCTURA;
GRANT CREATE TABLE ON SCHEMA CREDIBANCO_HOL.PLATAFORMA TO ROLE CRB_INFRAESTRUCTURA;
GRANT CREATE VIEW ON SCHEMA CREDIBANCO_HOL.PLATAFORMA TO ROLE CRB_INFRAESTRUCTURA;
GRANT CREATE DYNAMIC TABLE ON SCHEMA CREDIBANCO_HOL.PLATAFORMA TO ROLE CRB_INFRAESTRUCTURA;
GRANT CREATE TASK ON SCHEMA CREDIBANCO_HOL.PLATAFORMA TO ROLE CRB_INFRAESTRUCTURA;
GRANT CREATE PROCEDURE ON SCHEMA CREDIBANCO_HOL.PLATAFORMA TO ROLE CRB_INFRAESTRUCTURA;
GRANT CREATE FUNCTION ON SCHEMA CREDIBANCO_HOL.PLATAFORMA TO ROLE CRB_INFRAESTRUCTURA;
GRANT CREATE AGENT ON SCHEMA CREDIBANCO_HOL.PLATAFORMA TO ROLE CRB_INFRAESTRUCTURA;
GRANT CREATE CORTEX SEARCH SERVICE ON SCHEMA CREDIBANCO_HOL.PLATAFORMA TO ROLE CRB_INFRAESTRUCTURA;
GRANT CREATE STREAM ON SCHEMA CREDIBANCO_HOL.PLATAFORMA TO ROLE CRB_INFRAESTRUCTURA;
GRANT CREATE TABLE, CREATE VIEW, CREATE PROCEDURE ON SCHEMA CREDIBANCO_HOL.DCM_ARTIFACTS TO ROLE CRB_INFRAESTRUCTURA;
GRANT APPLY TAG ON ACCOUNT TO ROLE CRB_INFRAESTRUCTURA;
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE CRB_INFRAESTRUCTURA;

-- CRB_MIGRACION (Track 8)
GRANT USAGE ON DATABASE CREDIBANCO_HOL TO ROLE CRB_MIGRACION;
GRANT USAGE ON WAREHOUSE CREDIBANCO_HOL_WH TO ROLE CRB_MIGRACION;
GRANT ALL ON SCHEMA CREDIBANCO_HOL.MIGRACION TO ROLE CRB_MIGRACION;
GRANT USAGE ON SCHEMA CREDIBANCO_HOL.PAGOS TO ROLE CRB_MIGRACION;
GRANT USAGE ON SCHEMA CREDIBANCO_HOL.COMERCIOS TO ROLE CRB_MIGRACION;
GRANT SELECT ON ALL TABLES IN SCHEMA CREDIBANCO_HOL.PAGOS TO ROLE CRB_MIGRACION;
GRANT SELECT ON ALL TABLES IN SCHEMA CREDIBANCO_HOL.COMERCIOS TO ROLE CRB_MIGRACION;
GRANT SELECT ON FUTURE TABLES IN SCHEMA CREDIBANCO_HOL.PAGOS TO ROLE CRB_MIGRACION;
GRANT CREATE TABLE ON SCHEMA CREDIBANCO_HOL.MIGRACION TO ROLE CRB_MIGRACION;
GRANT CREATE VIEW ON SCHEMA CREDIBANCO_HOL.MIGRACION TO ROLE CRB_MIGRACION;
GRANT CREATE STAGE ON SCHEMA CREDIBANCO_HOL.MIGRACION TO ROLE CRB_MIGRACION;
GRANT CREATE PROCEDURE ON SCHEMA CREDIBANCO_HOL.MIGRACION TO ROLE CRB_MIGRACION;
GRANT CREATE FUNCTION ON SCHEMA CREDIBANCO_HOL.MIGRACION TO ROLE CRB_MIGRACION;
GRANT CREATE AGENT ON SCHEMA CREDIBANCO_HOL.MIGRACION TO ROLE CRB_MIGRACION;
GRANT CREATE CORTEX SEARCH SERVICE ON SCHEMA CREDIBANCO_HOL.MIGRACION TO ROLE CRB_MIGRACION;

-- Cross-track grants
GRANT USAGE ON SCHEMA CREDIBANCO_HOL.ANALITICA TO ROLE CRB_DATA_ANALYTICS;
GRANT USAGE ON SCHEMA CREDIBANCO_HOL.CUMPLIMIENTO TO ROLE CRB_DATA_ANALYTICS;
GRANT SELECT ON ALL TABLES IN SCHEMA CREDIBANCO_HOL.ANALITICA TO ROLE CRB_DATA_ANALYTICS;
GRANT SELECT ON ALL VIEWS IN SCHEMA CREDIBANCO_HOL.ANALITICA TO ROLE CRB_DATA_ANALYTICS;
GRANT SELECT ON ALL TABLES IN SCHEMA CREDIBANCO_HOL.CUMPLIMIENTO TO ROLE CRB_DATA_ANALYTICS;

-- Additional grants found during validation
GRANT CREATE STORAGE LIFECYCLE POLICY ON SCHEMA CREDIBANCO_HOL.PAGOS TO ROLE CRB_DATA_ANALYTICS;
GRANT CREATE STORAGE LIFECYCLE POLICY ON SCHEMA CREDIBANCO_HOL.PLATAFORMA TO ROLE CRB_DATA_ANALYTICS;
GRANT CREATE PROCEDURE ON SCHEMA CREDIBANCO_HOL.PLATAFORMA TO ROLE CRB_NEGOCIO;

-- ============================================================================
-- VALIDATED GRANTS (from 8-track parallel roleplay execution)
-- These grants were identified as missing when executing each track with its
-- designated role. Without these, participants get "Insufficient privileges".
-- ============================================================================
-- Track 1 (CRB_SEGURIDAD_INFO) - 13 missing
GRANT CREATE SNOWFLAKE.DATA_PRIVACY.CUSTOM_CLASSIFIER ON SCHEMA CREDIBANCO_HOL.GOBIERNO TO ROLE CRB_SEGURIDAD_INFO;
GRANT CREATE MASKING POLICY ON SCHEMA CREDIBANCO_HOL.GOBIERNO TO ROLE CRB_SEGURIDAD_INFO;
GRANT CREATE ROW ACCESS POLICY ON SCHEMA CREDIBANCO_HOL.GOBIERNO TO ROLE CRB_SEGURIDAD_INFO;
GRANT CREATE TABLE ON SCHEMA CREDIBANCO_HOL.GOBIERNO TO ROLE CRB_SEGURIDAD_INFO;
GRANT CREATE VIEW ON SCHEMA CREDIBANCO_HOL.GOBIERNO TO ROLE CRB_SEGURIDAD_INFO;
GRANT CREATE AGENT ON SCHEMA CREDIBANCO_HOL.GOBIERNO TO ROLE CRB_SEGURIDAD_INFO;
GRANT CREATE SEMANTIC VIEW ON SCHEMA CREDIBANCO_HOL.GOBIERNO TO ROLE CRB_SEGURIDAD_INFO;
GRANT CREATE CORTEX SEARCH SERVICE ON SCHEMA CREDIBANCO_HOL.GOBIERNO TO ROLE CRB_SEGURIDAD_INFO;
GRANT CREATE NETWORK RULE ON SCHEMA CREDIBANCO_HOL.GOBIERNO TO ROLE CRB_SEGURIDAD_INFO;
GRANT APPLY MASKING POLICY ON ACCOUNT TO ROLE CRB_SEGURIDAD_INFO;
GRANT APPLY ROW ACCESS POLICY ON ACCOUNT TO ROLE CRB_SEGURIDAD_INFO;
GRANT APPLY TAG ON ACCOUNT TO ROLE CRB_SEGURIDAD_INFO;
GRANT USAGE ON WAREHOUSE CREDIBANCO_HOL_WH TO ROLE CRB_SEGURIDAD_INFO;
GRANT OPERATE ON WAREHOUSE CREDIBANCO_HOL_WH TO ROLE CRB_SEGURIDAD_INFO;
GRANT SELECT ON ALL TABLES IN SCHEMA CREDIBANCO_HOL.PAGOS TO ROLE CRB_SEGURIDAD_INFO;
GRANT SELECT ON ALL TABLES IN SCHEMA CREDIBANCO_HOL.CLIENTES TO ROLE CRB_SEGURIDAD_INFO;
GRANT SELECT ON ALL TABLES IN SCHEMA CREDIBANCO_HOL.COMERCIOS TO ROLE CRB_SEGURIDAD_INFO;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA CREDIBANCO_HOL.GOBIERNO TO ROLE CRB_SEGURIDAD_INFO;

-- Track 3 (CRB_ARQUITECTURA) - 7 missing
GRANT CREATE DATABASE ROLE ON DATABASE CREDIBANCO_HOL TO ROLE CRB_ARQUITECTURA;
GRANT CREATE TABLE ON SCHEMA CREDIBANCO_HOL.COMERCIOS TO ROLE CRB_ARQUITECTURA;
GRANT CREATE VIEW ON SCHEMA CREDIBANCO_HOL.COMERCIOS TO ROLE CRB_ARQUITECTURA;
GRANT CREATE VIEW ON SCHEMA CREDIBANCO_HOL.ARQUITECTURA TO ROLE CRB_ARQUITECTURA;
GRANT USAGE ON SCHEMA CREDIBANCO_HOL.ARQUITECTURA TO ROLE CRB_ARQUITECTURA;
GRANT CREATE DYNAMIC TABLE ON SCHEMA CREDIBANCO_HOL.COMERCIOS TO ROLE CRB_ARQUITECTURA;
GRANT CREATE DATA METRIC FUNCTION ON SCHEMA CREDIBANCO_HOL.GOBIERNO TO ROLE CRB_ARQUITECTURA;
GRANT CREATE CORTEX SEARCH SERVICE ON SCHEMA CREDIBANCO_HOL.GOBIERNO TO ROLE CRB_ARQUITECTURA;
GRANT USAGE ON SCHEMA CREDIBANCO_HOL.GOBIERNO TO ROLE CRB_ARQUITECTURA;
GRANT SELECT ON ALL TABLES IN SCHEMA CREDIBANCO_HOL.GOBIERNO TO ROLE CRB_ARQUITECTURA;
GRANT USAGE ON WAREHOUSE CREDIBANCO_HOL_WH TO ROLE CRB_ARQUITECTURA;
GRANT OPERATE ON WAREHOUSE CREDIBANCO_HOL_WH TO ROLE CRB_ARQUITECTURA;
GRANT APPLY TAG ON ACCOUNT TO ROLE CRB_ARQUITECTURA;

-- Track 4 (CRB_ANALITICA) - 7 missing
GRANT CREATE TABLE ON SCHEMA CREDIBANCO_HOL.ANALITICA TO ROLE CRB_ANALITICA;
GRANT CREATE VIEW ON SCHEMA CREDIBANCO_HOL.ANALITICA TO ROLE CRB_ANALITICA;
GRANT CREATE CORTEX SEARCH SERVICE ON SCHEMA CREDIBANCO_HOL.CUMPLIMIENTO TO ROLE CRB_ANALITICA;
GRANT CREATE DYNAMIC TABLE ON SCHEMA CREDIBANCO_HOL.CUMPLIMIENTO TO ROLE CRB_ANALITICA;
GRANT USAGE ON SCHEMA CREDIBANCO_HOL.CUMPLIMIENTO TO ROLE CRB_ANALITICA;
GRANT SELECT ON ALL TABLES IN SCHEMA CREDIBANCO_HOL.CUMPLIMIENTO TO ROLE CRB_ANALITICA;
GRANT USAGE ON WAREHOUSE CREDIBANCO_HOL_WH TO ROLE CRB_ANALITICA;
GRANT OPERATE ON WAREHOUSE CREDIBANCO_HOL_WH TO ROLE CRB_ANALITICA;

-- Track 7 (CRB_INFRAESTRUCTURA) - 6 missing
GRANT CREATE ALERT ON SCHEMA CREDIBANCO_HOL.PLATAFORMA TO ROLE CRB_INFRAESTRUCTURA;
GRANT CREATE DYNAMIC TABLE ON SCHEMA CREDIBANCO_HOL.PLATAFORMA TO ROLE CRB_INFRAESTRUCTURA;
GRANT OPERATE ON WAREHOUSE CREDIBANCO_HOL_WH TO ROLE CRB_INFRAESTRUCTURA;
GRANT USAGE ON SCHEMA CREDIBANCO_HOL.PAGOS TO ROLE CRB_INFRAESTRUCTURA;
GRANT SELECT ON ALL TABLES IN SCHEMA CREDIBANCO_HOL.PAGOS TO ROLE CRB_INFRAESTRUCTURA;

-- Track 8 (CRB_MIGRACION) - 3 missing
GRANT CREATE TABLE ON SCHEMA CREDIBANCO_HOL.MIGRACION TO ROLE CRB_MIGRACION;
GRANT CREATE CORTEX SEARCH SERVICE ON SCHEMA CREDIBANCO_HOL.MIGRACION TO ROLE CRB_MIGRACION;
GRANT USAGE ON WAREHOUSE CREDIBANCO_HOL_WH TO ROLE CRB_MIGRACION;
GRANT OPERATE ON WAREHOUSE CREDIBANCO_HOL_WH TO ROLE CRB_MIGRACION;

-- Ownership transfers needed for masking policy demos
GRANT OWNERSHIP ON TABLE CREDIBANCO_HOL.PAGOS.LIQUIDACIONES TO ROLE CRB_SEGURIDAD_INFO COPY CURRENT GRANTS;

-- ============================================================================
-- 17. SEMAFORO
-- ============================================================================
SELECT 'MASTER_SETUP_DDL_OK' AS status;
