/* pre_warm.sql — Execute 30 minutes before HOL starts on each account
   Warms up warehouse, refreshes DTs, validates key services */
USE ROLE ACCOUNTADMIN;
USE WAREHOUSE CREDIBANCO_HOL_WH;
USE DATABASE CREDIBANCO_HOL;

-- 1. Warm up warehouse with a simple query
SELECT COUNT(*) FROM PAGOS.AUTORIZACIONES;

-- 2. Force refresh all Dynamic Tables
ALTER DYNAMIC TABLE PAGOS.DT_AUTORIZACIONES_SILVER_USER REFRESH;
ALTER DYNAMIC TABLE PAGOS.DT_HOURLY_USER REFRESH;
ALTER DYNAMIC TABLE PAGOS.DT_GOLD_FRAUDE_DIARIO REFRESH;
ALTER DYNAMIC TABLE PAGOS.DT_GOLD_KPI_COMERCIOS REFRESH;
ALTER DYNAMIC TABLE PAGOS.DT_GOLD_RESUMEN_CANAL REFRESH;

-- 3. Warm up Cortex AI (first call is slower)
SELECT SNOWFLAKE.CORTEX.AI_COMPLETE('mistral-7b', 'Di hola en español') AS warmup_cortex;

-- 4. Fetch latest from Git
ALTER GIT REPOSITORY CREDIBANCO_HOL.PLATAFORMA.HOL_REPO FETCH;

-- 5. Verify key counts
SELECT 'AUTORIZACIONES' AS tabla, COUNT(*) AS rows FROM PAGOS.AUTORIZACIONES
UNION ALL SELECT 'COMERCIOS', COUNT(*) FROM COMERCIOS.COMERCIOS
UNION ALL SELECT 'TARJETAHABIENTES', COUNT(*) FROM CLIENTES.TARJETAHABIENTES
UNION ALL SELECT 'DT_SILVER', COUNT(*) FROM PAGOS.DT_AUTORIZACIONES_SILVER_USER
UNION ALL SELECT 'DT_GOLD_FRAUDE', COUNT(*) FROM PAGOS.DT_GOLD_FRAUDE_DIARIO
UNION ALL SELECT 'TRAIN_ANOMALIAS', COUNT(*) FROM ANALITICA.TRAIN_ANOMALIAS;

SELECT '🔥 PRE-WARM COMPLETE' AS status, CURRENT_ACCOUNT() AS account, CURRENT_TIMESTAMP() AS ts;
