/* validate_readiness.sql — Run on each account BEFORE the HOL to verify everything works
   Execute as ACCOUNTADMIN. All checks should return OK. */
USE ROLE ACCOUNTADMIN;
USE WAREHOUSE CREDIBANCO_HOL_WH;
USE DATABASE CREDIBANCO_HOL;

-- 1. Core tables with data
SELECT 'T0_SCHEMAS' AS CHECK_ID,
  CASE WHEN cnt >= 13 THEN '✅ OK' ELSE '❌ FAIL: ' || cnt || ' schemas' END AS RESULT
FROM (SELECT COUNT(*) cnt FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME NOT IN ('INFORMATION_SCHEMA','PUBLIC'));

SELECT 'T0_AUTORIZACIONES' AS CHECK_ID,
  CASE WHEN cnt > 0 THEN '✅ OK (' || cnt || ' rows)' ELSE '❌ FAIL: 0 rows' END AS RESULT
FROM (SELECT COUNT(*) cnt FROM PAGOS.AUTORIZACIONES);

SELECT 'T0_COMERCIOS' AS CHECK_ID,
  CASE WHEN cnt > 0 THEN '✅ OK (' || cnt || ' rows)' ELSE '❌ FAIL: 0 rows' END AS RESULT
FROM (SELECT COUNT(*) cnt FROM COMERCIOS.COMERCIOS);

SELECT 'T0_TARJETAHABIENTES' AS CHECK_ID,
  CASE WHEN cnt > 0 THEN '✅ OK (' || cnt || ' rows)' ELSE '❌ FAIL: 0 rows' END AS RESULT
FROM (SELECT COUNT(*) cnt FROM CLIENTES.TARJETAHABIENTES);

-- 2. Governance objects (T1)
SELECT 'T1_TAGS' AS CHECK_ID,
  CASE WHEN cnt >= 8 THEN '✅ OK (' || cnt || ' tags)' ELSE '❌ FAIL: ' || cnt || ' tags' END AS RESULT
FROM (SELECT COUNT(*) cnt FROM TABLE(RESULT_SCAN(LAST_QUERY_ID())));
SHOW TAGS IN DATABASE CREDIBANCO_HOL;
SELECT 'T1_TAGS' AS CHECK_ID, '✅ ' || COUNT(*) || ' tags' AS RESULT FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

SHOW MASKING POLICIES IN DATABASE CREDIBANCO_HOL;
SELECT 'T1_MASKING' AS CHECK_ID,
  CASE WHEN COUNT(*) >= 5 THEN '✅ OK (' || COUNT(*) || ' policies)' ELSE '❌ FAIL' END AS RESULT
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

SHOW ROW ACCESS POLICIES IN DATABASE CREDIBANCO_HOL;
SELECT 'T1_RAP' AS CHECK_ID,
  CASE WHEN COUNT(*) >= 2 THEN '✅ OK (' || COUNT(*) || ' RAPs)' ELSE '❌ FAIL' END AS RESULT
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

SHOW DATA METRIC FUNCTIONS IN DATABASE CREDIBANCO_HOL;
SELECT 'T1_DMF' AS CHECK_ID,
  CASE WHEN COUNT(*) >= 1 THEN '✅ OK' ELSE '❌ FAIL: no DMF' END AS RESULT
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

-- 3. Pipelines (T2)
SHOW DYNAMIC TABLES IN DATABASE CREDIBANCO_HOL;
SELECT 'T2_DTS' AS CHECK_ID,
  CASE WHEN COUNT(*) >= 5 THEN '✅ OK (' || COUNT(*) || ' DTs)' ELSE '❌ FAIL: ' || COUNT(*) || ' DTs' END AS RESULT
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

SHOW TASKS IN DATABASE CREDIBANCO_HOL;
SELECT 'T2_TASKS' AS CHECK_ID,
  CASE WHEN COUNT(*) >= 5 THEN '✅ OK (' || COUNT(*) || ' tasks)' ELSE '❌ FAIL: ' || COUNT(*) || ' tasks' END AS RESULT
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

SHOW STREAMS IN DATABASE CREDIBANCO_HOL;
SELECT 'T2_STREAMS' AS CHECK_ID,
  CASE WHEN COUNT(*) >= 1 THEN '✅ OK' ELSE '❌ FAIL: no streams' END AS RESULT
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

SHOW DBT PROJECTS IN DATABASE CREDIBANCO_HOL;
SELECT 'T2_DBT' AS CHECK_ID,
  CASE WHEN COUNT(*) >= 1 THEN '✅ OK (' || COUNT(*) || ' projects)' ELSE '❌ FAIL: no dbt' END AS RESULT
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

SHOW GIT REPOSITORIES IN DATABASE CREDIBANCO_HOL;
SELECT 'T2_GIT' AS CHECK_ID,
  CASE WHEN COUNT(*) >= 1 THEN '✅ OK' ELSE '❌ FAIL: no git repo' END AS RESULT
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

-- 4. AI/ML (T4)
SHOW AGENTS IN DATABASE CREDIBANCO_HOL;
SELECT 'T4_AGENTS' AS CHECK_ID,
  CASE WHEN COUNT(*) >= 3 THEN '✅ OK (' || COUNT(*) || ' agents)' ELSE '❌ FAIL: ' || COUNT(*) || ' agents (need 3)' END AS RESULT
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

SHOW CORTEX SEARCH SERVICES IN DATABASE CREDIBANCO_HOL;
SELECT 'T4_CORTEX_SEARCH' AS CHECK_ID,
  CASE WHEN COUNT(*) >= 2 THEN '✅ OK (' || COUNT(*) || ' services)' ELSE '❌ FAIL: ' || COUNT(*) END AS RESULT
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

SHOW SEMANTIC VIEWS IN DATABASE CREDIBANCO_HOL;
SELECT 'T4_SEMANTIC_VIEWS' AS CHECK_ID,
  CASE WHEN COUNT(*) >= 2 THEN '✅ OK (' || COUNT(*) || ' SVs)' ELSE '❌ FAIL: ' || COUNT(*) END AS RESULT
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

SHOW MODELS IN DATABASE CREDIBANCO_HOL;
SELECT 'T4_MODELS' AS CHECK_ID,
  CASE WHEN COUNT(*) >= 2 THEN '✅ OK (' || COUNT(*) || ' models)' ELSE '❌ FAIL: ' || COUNT(*) || ' (run SETUP notebooks)' END AS RESULT
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

-- 5. BI/Dashboards (T6)
SHOW STREAMLITS IN DATABASE CREDIBANCO_HOL;
SELECT 'T6_STREAMLITS' AS CHECK_ID,
  CASE WHEN COUNT(*) >= 3 THEN '✅ OK (' || COUNT(*) || ' apps)' ELSE '❌ FAIL: ' || COUNT(*) END AS RESULT
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

SHOW SHARES;
SELECT 'T6_SHARES' AS CHECK_ID,
  CASE WHEN COUNT(*) >= 1 THEN '✅ OK (' || COUNT(*) || ' shares)' ELSE '❌ FAIL: no shares' END AS RESULT
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID())) WHERE "kind" = 'OUTBOUND';

-- 6. FinOps (T7)
SHOW RESOURCE MONITORS;
SELECT 'T7_RESOURCE_MONITORS' AS CHECK_ID,
  CASE WHEN COUNT(*) >= 1 THEN '✅ OK' ELSE '❌ FAIL: no resource monitors' END AS RESULT
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

SHOW ALERTS IN DATABASE CREDIBANCO_HOL;
SELECT 'T7_ALERTS' AS CHECK_ID,
  CASE WHEN COUNT(*) >= 3 THEN '✅ OK (' || COUNT(*) || ' alerts)' ELSE '❌ FAIL: ' || COUNT(*) END AS RESULT
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

-- 7. Iceberg (T0/T2)
SHOW ICEBERG TABLES IN DATABASE CREDIBANCO_HOL;
SELECT 'T0_ICEBERG' AS CHECK_ID,
  CASE WHEN COUNT(*) >= 1 THEN '✅ OK' ELSE '❌ FAIL: no iceberg tables' END AS RESULT
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

-- 8. Roles granted to USER
SHOW GRANTS TO USER USER;
SELECT 'ROLES_USER' AS CHECK_ID,
  CASE WHEN COUNT(*) >= 8 THEN '✅ OK (' || COUNT(*) || ' roles)' ELSE '⚠️ CHECK: ' || COUNT(*) || ' roles' END AS RESULT
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID())) WHERE "role" IS NOT NULL AND "role" != 'None';

-- 9. Cortex AI test
SELECT 'CORTEX_AI' AS CHECK_ID,
  CASE WHEN LEN(SNOWFLAKE.CORTEX.AI_COMPLETE('mistral-7b', 'say OK')) > 0 THEN '✅ OK' ELSE '❌ FAIL' END AS RESULT;

-- Final
SELECT '🏁 VALIDATION COMPLETE' AS CHECK_ID, CURRENT_ACCOUNT() || ' @ ' || CURRENT_TIMESTAMP()::VARCHAR AS RESULT;
